stratum-mining/stratum

- utils/buffer/Cargo.toml
- utils/buffer/README.md
- utils/buffer/benches/pool_benchmark.rs
- utils/buffer/src/buffer_pool/mod.rs
InnerMemery used to do a memcpy to move the raw part around when the
index change. The implementation was sound but also UB. Now it use
Vec.copy_within so is no more UB and 2 unsafe block are removed from the code.
> Updadate BufferPool, remove unsafe.

- .github/workflows/coverage.yaml
- .github/workflows/rust.yaml
- .github/workflows/sv2-header-check.yaml
- roles/v2/mining-proxy/src/lib/upstream_mining.rs
Addresses issue #75.
Uses [`cargo tarpaulin`](https://github.com/xd009642/tarpaulin) to perform code coverage as a GitHub Action. One note of possible concern with this library: it only operates natively on linux. Imo, it works for our purposes as it runs just fine with `ubuntu-latest` on GitHub Actions and has docker support. 
Right now, the coverage report shows: `31.25% coverage, 2139/6845 lines covered`.  Therefore, in the `.github/workflows/coverage.yaml` file, the `fail-under` flag is set to 31%. As more tests are added, this number should be increased.
Also, renamed the other GitHub Actions to better reflect their action.
> Add code coverage to GitHub Actions

- protocols/v2/messages-sv2/Cargo.toml
`cargo check` was failing with these errors:
```
➜  stratum git:(main) cargo check
Checking mining_sv2 v0.1.0 (/Users/rachelrybarczyk/Development/StratumV2/Dev/stratum/protocols/v2/subprotocols/mining)
error[E0599]: no method named `inner_as_ref` found for enum `binary_codec_sv2::datatypes::non_copy_data_types::inner::Inner<'a, true, 32_usize, 0_usize, 0_usize>` in the current scope
--> protocols/v2/subprotocols/mining/src/lib.rs:208:23
|
208 |         let inner = v.inner_as_ref();
|                       ^^^^^^^^^^^^ method not found in `binary_codec_sv2::datatypes::non_copy_data_types::inner::Inner<'a, true, 32_usize, 0_usize, 0_usize>`
error[E0599]: no method named `inner_as_ref` found for enum `binary_codec_sv2::datatypes::non_copy_data_types::inner::Inner<'a, true, 32_usize, 0_usize, …
```
> Set default-features to true in messages-sv2 Cargo toml so cargo compiles

- .github/workflows/sv2-header-check.yaml
- .github/workflows/test-lint.yaml
- build_header.sh
- protocols/v2/binary-sv2/binary-sv2/src/lib.rs
- protocols/v2/subprotocols/common-messages/src/setup_connection.rs
- protocols/v2/subprotocols/template-distribution/src/new_template.rs
- protocols/v2/subprotocols/template-distribution/src/request_transaction_data.rs
- protocols/v2/subprotocols/template-distribution/src/set_new_prev_hash.rs
- protocols/v2/subprotocols/template-distribution/src/submit_solution.rs
- protocols/v2/sv2-ffi/src/lib.rs
- rust-toolchain.toml
- sv2-header-check.sh
Crates in this workspace must be buildable on guix, for that the
required rust version is lowered to one supported on guix.
> Fix guix build

- protocols/v2/roles-logic-sv2/src/parsers.rs
- protocols/v2/subprotocols/job-negotiation/src/allocate_mining_job.rs
- protocols/v2/subprotocols/job-negotiation/src/commit_mining_job.rs
Use u32 instead of B0_255 to semplify implementation, 2^32 tokens per
proxy are enough.
> Update JobNegotiation mining_job_token

- .github/workflows/coverage.yaml
- Fixes the GitHub Actions that performs test coverage
- Uses [`cargo-tarpaulin`](https://github.com/xd009642/tarpaulin) to estimate coverage and posts results to the project's [codecov page](https://app.codecov.io/gh/stratum-mining/stratum).
- `cargo-tarpaulin` only support actions built on x86_64 processors running Linux at the time of this PR
- Estimates coverage with the command: `cargo +nightly tarpaulin --verbose --features prop_test noise_sv2 fuzz with_buffer_pool async_std debug tokio with_tokio derive_codec_sv2 binary_codec_sv2 default core with_serde --lib --exclude-files examples/* --timeout 120 --fail-under 41 --out Xml`
- `-- features`: Includes the code with the listed features. The following features result in a `tarpaulin` error and are NOT included: `derive`, `alloc`, …
> Fix GH Action code coverage workflow

- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/handlers/mod.rs
- roles/v2/mining-proxy/src/lib/downstream_mining.rs
- roles/v2/mining-proxy/src/lib/upstream_mining.rs
- roles/v2/pool/src/lib/mining_pool/message_handler.rs
- roles/v2/pool/src/lib/mining_pool/mod.rs
- roles/v2/pool/src/lib/mining_pool/setup_connection.rs
- roles/v2/pool/src/lib/template_receiver/message_handler.rs
- roles/v2/pool/src/lib/template_receiver/mod.rs
- roles/v2/test-utils/mining-device/src/main.rs
- roles/v2/test-utils/pool/src/main.rs
- Adds a new `RelaySameMessageToSv1` variant to the `SendTo` enum
- Used to support message handling in applications that use both SV1 + SV2 protocols, like a SV1 <-> SV2 translator proxy
- Renames `RelaySameMessage` variant to `RelaySameMessageToSv2`
- Renames `RelayNewMessage` variant to `RelayNewMessageToSv2`
- Updates `protocols/v2/roles-logic-sv2/src/handlers/mod.rs` doc comments
> Add RelaySameMessageToSv1 variant to SendTo

- roles/translator/src/downstream_sv1/downstream.rs
- roles/translator/src/proxy/bridge.rs
- roles/translator/src/proxy/next_mining_notify.rs
- roles/translator/src/upstream_sv2/upstream.rs
The Translator Proxy only supports `future_job=true`. This works with the current Braiins pool behavior as it only sends future jobs. This PR handles the case when `future_job=false`.
It is worth noting that there has been a [spec change](https://github.com/stratum-mining/sv2-spec/pull/12) that removes the `future_job` field from the mining job messages and replaces it with `min_ntime`. Once this PR has been reviewed and merged, another PR will be opened to migrate from `future_job`s to `min_ntime`. This change also impacts SRI's pool application and will need to be updated there as well.
> TProxy future job handling

- utils/message-generator/src/external_commands.rs
Now it is possible to launch commands from mg directory. If a command start with cargo and has one argument, it is performed in the mg directory, otherwise in the main directory. This is because mg is not the main workspace"
> Add possibility to launch commands from mg directory

- roles/translator/src/proxy/bridge.rs
closes https://github.com/stratum-mining/stratum/issues/362
The implementation fixes translation from `mining.submit` (without version rolling) to `SubmitSharesExtended` by retaining the previous job in the `Bridge.job_mapper` instead of removing it. Then, during translation, if the `mining.submit` message does not contain a version field, it looks for a the job with the matching `job_id` in `job_mapper` to insert the stored job's version into the SV2 `SubmitSharesExtended` message.
Note: I testing this implementation successfully against the pool role and an sv1 cpuminer before the addition of the channel factory, meaning `translate_submit` would always find the respective job and populate the missing `version` field . Since the pool role now does not support extended channels, the …
> Fix: NoSv1VersionBits

- protocols/v2/subprotocols/mining/src/lib.rs
- roles/translator/src/upstream_sv2/upstream.rs
This fixes the target compare bug - https://github.com/stratum-mining/stratum/issues/400
I also added a unit test to verify (it breaks with the old code).
> Target compare bug

- test/message-generator/messages/common_messages.json
- test/message-generator/mock/template-provider-mock0.json
- utils/message-generator/src/parser/frames.rs
- utils/message-generator/src/parser/sv2_messages.rs
Through the function message_from_path it is now possible to separate part of tests in different test module. This is applied to the mock of the template provider, where the common messages are moved to /tests/message-generator/messages/common_messages.json.
Also, some documentation is added.
> Add modularity for messages MG

- test/message-generator/test/it_open_test.json
- test/message-generator/test/pool-sri-test-1.json
- utils/message-generator/Cargo.lock
- utils/message-generator/src/executor.rs
- utils/message-generator/src/main.rs
- utils/message-generator/src/parser/actions.rs
This PR introduces a field of the actions that is called "actiondoc". For each action of a test, the actiondoc is a small description of the operations performed by the action. When an action is performed, the relative actiondoc is printed out. The only two tests available are modified and now have actiondocs.
> Mg add doc to actions

- Cargo.lock
- roles/translator/Cargo.toml
- roles/translator/src/downstream_sv1/downstream.rs
- roles/translator/src/downstream_sv1/mod.rs
- roles/translator/src/error.rs
- roles/translator/src/main.rs
- roles/translator/src/proxy/bridge.rs
- roles/translator/src/status.rs
- roles/translator/src/upstream_sv2/upstream.rs
- utils/error-handling/src/lib.rs
closes https://github.com/stratum-mining/stratum/issues/412 ,
but we should still make the conversion completely to tokio and remove dependencies on `futures` and `async_std` and `async_channel`. `async_channel` and `async_std` are required for the `network_helpers` as well, so we would need to make changes there as well
!This should be merged after https://github.com/stratum-mining/stratum/pull/395. After I will rebase and fix conflicts!
NOTE: The shutdown timeout was added since clients that send `mining.subscribe` and never send `mining.authorize` after would result in the TCP connection to never be shutdown since `is_authorized` is a condition on the two notify task conditional branches that sends data to the client. Once is authorized is set, every incoming `Notify` message will …
> TProxy: Downstream Kill Switch

- utils/message-generator/Cargo.lock
- utils/message-generator/test.json
solves #414 
Changes include:
- use of fi3's TP instance in the pool's configs to remove bitcoind and bitcoin-cli from setup_commands
- ^ this also eliminated the need for any cleanup_commands
- restructured action results to work with current SRI code
- updated "doc" section to reflect all changes
> Fixed test.json to work with current main

- .github/workflows/coverage.yaml
- mg-codecov-tests.sh
- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- rust-toolchain.toml
- test/config/proxy-config-test-multiple-upstreams-extended-jn.toml
- test/config/proxy-config-test-multiple-upstreams-extended.toml
- test/config/proxy-config-test-multiple-upstreams.toml
- test/message-generator/cov/cov_test.json
- utils/message-generator/README.md
This change:
1.) Adds a new Message Generator test to test/message-generator/cov for generating a coverage report
2.) Runs this test in .github/workflows/coverage.yaml to generate report, and upload it to codecov with the existing tarpaulin report
3.) Includes information on the cargo-llvm-cov package in the Message Generator README
> Add coverage from message generator to coverage action

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/job_creator.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/subprotocols/mining/src/new_mining_job.rs
- roles/translator/conf/tproxy-config-local.toml
- roles/translator/proxy-config.toml
- roles/translator/src/downstream_sv1/diff_management.rs
- roles/translator/src/downstream_sv1/downstream.rs
- roles/translator/src/downstream_sv1/mod.rs
- roles/translator/src/main.rs
- roles/translator/src/proxy/bridge.rs
- roles/translator/src/proxy/next_mining_notify.rs
- roles/translator/src/upstream_sv2/upstream.rs
- roles/v2/pool/src/lib/mining_pool/message_handler.rs
- roles/v2/pool/src/lib/template_receiver/mod.rs
- roles/v2/test-utils/mining-device/src/main.rs
before this, we were creating a new "channel" for each downstream connection in the TProxy for easier tracking, but we were opening every channel with channel_id 1, which caused each share submission to check shares with the wrong extranonce. Now we are storing a separate channel_id for each connection in the `Downstream` struct, and a new wrapper type `SubmitSharesWithId` was added that gets sent to the `Bridge` so it can properly look up the correct channel.
According to BIP-141 the txid is the same for segwit and legacy transactions because the txid remains as the SHA256d hash of the serialized legacy transaction (excludes segwit the specific fields `marker`, `flag` and `witness` data). The shares created by a cpuminer would not match that of the miner because we were sending segwit …
> Fix: Share Hash Calcs and Other Bugs

- protocols/v1/src/lib.rs
- protocols/v1/src/methods/mod.rs
- protocols/v1/src/utils.rs
- protocols/v2/codec-sv2/src/decoder.rs
- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- protocols/v2/subprotocols/template-distribution/src/new_template.rs
- roles/translator/proxy-config.toml
The whatsminer starts out with a mining.suggest_difficulty message which previously we errored on and dropped the connection. This change simply ignores the message which is sv1 spec compatible. Eventually we should implement the correct response to the message.
I also change the Share Hash output to a hex string so it's easier to look up on block explorer the block that gets confirmed.
> Fixes tproxy when using WhatsMiner (or miner that uses mining.suggest_difficulty)

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- roles/translator/proxy-config.toml
- roles/translator/src/proxy/bridge.rs
- roles/translator/src/proxy/next_mining_notify.rs
- roles/translator/src/proxy_config.rs
- roles/v2/mining-proxy/proxy-config.toml
- roles/v2/mining-proxy/src/lib/upstream_mining.rs
- roles/v2/mining-proxy/src/main.rs
- roles/v2/test-utils/mining-device/src/main.rs
- test/config/proxy-config-test-multiple-upstreams-extended-jn.toml
- test/config/proxy-config-test-multiple-upstreams-extended.toml
- test/config/proxy-config-test-multiple-upstreams.toml
- test/config/tproxy-config-no-jn-sv1-cpu-md.toml
- test/message-generator/test/pool-sri-test-extended_0.json
TP has been fixed so that SNPH and NEMJ messages order is no more inverted, this updated the SRI codebase to work with the new TP. Also fix JN issues in the tproxy and the minig-prox.
> Updated SRI codebase to work with fixed TP, Fix minor issues

- roles/translator/src/proxy_config.rs
Proxy users shouldn't be mucking with this test only flag so let's hide it by not including it in the example config and making the default false. Without this the tproxy panics using the default example config:
`
thread 'main' panicked at 'called Result::unwrap() on an Err value: BadTomlDeserialize(Error { inner: ErrorInner { kind: Custom, line: Some(45), col: 0, at: Some(1538), message: "missing field test_only_share_withhold", key: [] } })', roles/translator/src/main.rs:49:43`
> Make the default false for test_only_share_withhold

- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/b032.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/sequences/seq064k.rs
- protocols/v2/binary-sv2/serde-sv2/src/ser.rs
- roles/pool/Cargo.toml
- test/config/tproxy-config-no-jd-sv1-cpu-md.toml
- test/message-generator/test/pool-sri-test-close-channel.json
- test/message-generator/test/translation-proxy.json
- utils/message-generator/Cargo.lock
- utils/message-generator/src/executor.rs
- utils/message-generator/src/into_static.rs
- utils/message-generator/src/main.rs
- utils/message-generator/src/parser/actions.rs
- utils/message-generator/src/parser/frames.rs
- utils/message-generator/src/parser/mod.rs
- utils/message-generator/src/parser/sv2_messages.rs
In test pool-sri-test-reject-auth.json the pool is launched with the
ferature MG-reject-auth. A little modification to the pool toml is added
to make this feature work and the test pass.
The test translation-proxy.json has a OpenExtendedMiningChannelSuccess
message with request_id = 666.i If you run it, you see that the message
is sent with the request_id field that is equal to the same field in the
message OpenExtendedMiningChannel previously received, namely 0.
This is done by a
a field "replace_fields" in the json test message. Replace fields is a
vector of objects of type ("field", "variable_name"). In this case, it is
just ("request_id", "variable_name"). In the actions, there is a new action
result called GetMessageField. This result is defined by a SV2 protocol, a
message_type and …
> Mg stateful tests

- protocols/v2/subprotocols/job-declaration/src/commit_mining_job.rs
- utils/message-generator/Cargo.lock
- utils/message-generator/src/executor.rs
- utils/message-generator/src/into_static.rs
FIRST: in the implementation of GetSize of CommitMiningJob in JD protocol, there were
some bugs, like "coninbase" in place of "coinbase". The compiling of this
part of software is disabled by default, unless compiling with the
feature "with_serde". This is why these issues do not appear in normal compiling.
SECOND: iin PR 587, some JD messages are added to the SRI, so their correspectives
in the MG are added
> Fix small bugs after pr 587

- test/message-generator/test/translation-proxy.json
- utils/message-generator/src/executor.rs
- utils/message-generator/src/into_static.rs
- utils/message-generator/src/main.rs
- utils/message-generator/src/parser/actions.rs
- utils/message-generator/src/parser/frames.rs
- utils/message-generator/src/parser/mod.rs
- utils/message-generator/src/parser/sv2_messages.rs
FIRST COMMIT:
ReplaceField struct
The messages came along with a vector of (String, String), where the
first entry is the field_name to be replaced and the second is the
keyword associated. This is replaced with a much more human readable
struct Replacefield {
field_name: String,
keyword: String
}
SECOND COMMIT:
improve code tests
- one test did't pass and now it is fixed
- add a second test that checks on a sv2 message that the composition
(serialization and then deserialization) is the identity
THIRD COMMIT:
SaveField string
In GetMessageField, the field "fields" that represents the fields that
must be saved from the message is Vec<(String, Strin)>, where first
entry is the the field_id and the second is the keyword to retrieve the
first. Now a more suitable struct
SaveField {
field_id: …
> Mg replacefield struct and code tests

- protocols/v2/subprotocols/job-declaration/src/identify_transactions.rs
Remove reduntant wrong code in protocols/v2/subprotocols/job-declaration/src/identify_transactions.rs
> Fix remove redundant field in IdentifyTransactions

- Cargo.lock
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/seq_inner.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/b016m.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/sequences/seq064k.rs
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/utils.rs
- roles/jd-client/src/downstream.rs
- roles/jd-client/src/job_declarator/mod.rs
- roles/jd-client/src/main.rs
- roles/jd-client/src/template_receiver/mod.rs
- utils/message-generator/Cargo.lock
---recreate PR because it was created on wrong branch---
Add functionality for the DeclareMiningJob message for the values: tx_short _hash _list and tx_hash_list_hash. These are required to let the JD server to propagate the block by checking the transactions hashes against its own TP or mempool. If they are not present IdentifyTransactions message will be sent by the JD server to retrive the missing transactions.
> Jd short hash

- .github/workflows/coverage.yaml
- .gitignore
- README.md
- tarpaulin.toml
after #197 and #203 , `cargo-tarpaulin` performs test coverage via:
```
$ cargo +nightly tarpaulin --verbose --features disable_nopanic prop_test noise_sv2 fuzz with_buffer_pool async_std debug tokio with_tokio derive_codec_sv2 binary_codec_sv2 default core --lib --exclude-files examples/* --timeout 120 --fail-under 30 --out Xml
```
as requiested by @rrybarczyk in https://github.com/stratum-mining/stratum/issues/115, this PR adds a `tarpaulin.toml` file to the root of the project
with this PR, now the following is sufficient:
```
$ cargo +nightly tarpaulin --verbose
```
---
close #115
> tarpaulin config file

- roles/jd-client/src/upstream_sv2/upstream.rs
- roles/translator/src/downstream_sv1/diff_management.rs
- roles/translator/src/proxy/next_mining_notify.rs
From dev notes:
```
Timestamp issue - we should look into it
- Every block we mine have the same timestamp as the previous block
- New block is mined TP sees it and sends a current template, downstream doesn’t change the timestamp (JDC, translator      nor the mining machine)
- When downstream receives a new template it can create a job with updated timestamp
- Translator proxy should add this;
```
This PR fixes this issue, giving to the mining-device the most updated timestamp
> Fix outdated timestamp

- protocols/v2/sv2-ffi/src/lib.rs
- protocols/v2/sv2-ffi/sv2.h
close https://github.com/stratum-mining/stratum/issues/166
in this PR we are making `Sv2Error::PayloadTooBig` into `Sv2Error::PayloadTooBig(*const std::ffi::c_char)` so that it can carry `message`.
as @rrybarczyk put it on the original issue description:
> This will help tremendously with better understanding error messages for the sv2 bindings.
---
Note 1: this PR is not doing `Sv2Error::PayloadTooBig(String)` like it was suggested on the original issue description.
`*const std::ffi::c_char` was chosen instead of `String` for easier `cbindgen` compatibility. If `String` is used, `sv2.h` has incomplete type ‘String’ and compilation of `examples/interop-cpp/template-provider/template-provider.cpp` breaks as a consequence.
---
Note 2: this PR is not modifying `trait Frame` like it was …
> FFI: pass in `message` to `Sv2Error::PayloadTooBig` variant

- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/noise-sv2/src/handshake.rs
- protocols/v2/noise-sv2/src/initiator.rs
- protocols/v2/noise-sv2/src/responder.rs
- protocols/v2/noise-sv2/src/signature_message.rs
No other changes.
Only tested with `cargo test` in `roles/pool`.
> Noise: bump secp256k1 to v0.28.1

- protocols/v2/roles-logic-sv2/src/utils.rs
Configuring a Taproot output for the coinbase currently expects a regular public key:
```toml
coinbase_outputs = [
{ output_script_type = "P2TR", output_script_value = "..." },
]
```
In order to extract the public key from a Bitcoin Core wallet, you'll need to do something like `getaddressinfo tr…` which will give you the _x-only_ public key. Same if you get the output descriptor.
This PR makes life easier by parsing an x-only pubkey.
> Parse x-only pubkey for P2TR coinbase output

- roles/jd-client/src/lib/job_declarator/mod.rs
- test/config/jds-stack-overflow/jdc-config.toml
- test/config/jds-stack-overflow/mining-proxy-config.toml
- test/config/jds-stack-overflow/pool-config.toml
- test/message-generator/mock/jds-mock-no-token.json
- test/message-generator/test/jds-do-not-stackoverflow-when-no-token.json
https://github.com/stratum-mining/stratum/issues/688 has an extensive discussion around a Stack Overflow happening on JDC.
As @GitGab19 pointed out:
* JDC sends a `DeclareMiningJob` message to JDS
* JDS for some unknown reason takes some seconds to answer with a `DeclareMiningJobSuccess` message to JDC
* in the meantime, the JDC creates a new MiningJob (because a NewTemplate arrived from TP)
* JDC's call to `Self::start_templates` initiates a call to `Self::get_last_token`.
* `Self::get_last_token` checks `self.allocated_tokens.len()`, and in case it is `0`, it recursively calls itself, in order to eventually fill `self.allocated_tokens` and have something to work with. That will eventually happen, because `Self::get_last_token` always calls `Self::allocate_tokens`, which sends a …
> fix JDC stack overflow

- clippy-on-all-workspaces.sh
If we want to compile all the workspaces, we must do it for each separately. This is annoying and not practical.
This PR adds a small script that compiles all the workspaces sequentially and return an error if there are warnings or error
> Clippy on all worskpaces at once

- protocols/v2/noise-sv2/src/cipher_state.rs
> Fix noise-handshake operations order

- roles/Cargo.lock
- roles/translator/Cargo.toml
- roles/translator/src/lib/downstream_sv1/downstream.rs
- roles/translator/src/lib/error.rs
- roles/translator/src/lib/status.rs
Update the translator so that it do not accept any line from downstream but only the ones shorter then 2^16 bytes. Doing that it remove a possible vector for a dos attack. It must be said that translator is supposed to be used by miner in their local network with their mining device so I'm not sure how much useful this patch can be.
Unfortunately `async_std` do not have the equivalent of `tokio_util::codec::LineCodec` (not sure if out there there is something that can be used) so i had to implement the logic manually. Should be optimized enough. If we want better performance we can open a new PR.   
EDIT:
didn't notice PR #429 it seems that we can just use `LineCodec` from `tokio_util` I will remove the manual implementation and use that one, and force push it.
> Update: translator do not accept bigger than 64K bytes lines from downstream

- .github/workflows/run-and-track-benchmarks-on-main.yaml
- .github/workflows/run-benchmarks.yaml
- .github/workflows/track-benchmarks.yaml
I added a new workflow to be executed every time we merge new PRs on main branch.
In this way we can maintain a better tracking of benchmarks executed on the main branch, visualizing them on [bencher.dev](https://bencher.dev/console/projects/stratum-v2-sri/perf?key=true&reports_per_page=4&branches_per_page=8&testbeds_per_page=8&benchmarks_per_page=8&reports_page=1&branches_page=2&testbeds_page=1&benchmarks_page=4&testbeds=057e03a0-be5a-4804-9dc0-9f914c196040%2C6e5299a9-5f8e-48db-b3e9-d0be3f592002&benchmarks=e99d34e3-9906-4ff4-9bda-b28360edf0fe%2C986d5bb7-2a50-443a-8c63-0c9d0a4eaf7c%2C0718860c-1091-41cf-be7e-1d4876b5fe79%2C41389b77-4f6b-4abc-a69b-44f73dddbc21%2C0372bad6-fe36-4b12-86b2-49f321a6bf50%2C8c7d8e76-33b4-4eef-87ef-1bf184855e6b%2Ca5429b2b-f710-4e7d-b6cc-3b5114804250%2C3290a515-f290- …
> Baseline benchmarks on bencher for main branch

- build-on-all-workspaces.sh
this PR follows a [suggestion](https://github.com/stratum-mining/stratum/pull/761/files#r1495079458) by @plebhash during the review of [PR761](https://github.com/stratum-mining/stratum/pull/761/). This should be merged *before* PR761 (because already includes this script)
WHAT THIS PR DOES:
after that the SRI has been divided in several workspaces for external consuption, it is annoying to compile every workspace manually. So, a script named clippy-on-all-workspaces.sh has been added. This script is mean to aid the the final phase of developing a feature, where build compiles and we pass to clippy.
In a preliminary phase of developing though, it is necessary something that compiles a bit less deep and we do want to make tests pass. Thats why I propose this script that does exactly this: …
> easy script for compiling during development

- .github/workflows/run-and-track-benchmarks-on-main.yaml
I just updated the bencher project name to stratum-v2-sri (which is the newest one on bencher.dev) in the `Run and Track Benchmarks On Main` workflow file.
> Bencher project name updated in `Run and Track Benchmarks On Main`

- roles/jd-client/config-examples/jdc-config-hosted-example.toml
- roles/pool/config-examples/pool-config-hosted-tp-example.toml
This PR fixes the `authority_public_key` for our hosted TP, so that testers can correctly use again the `jdc-config-hosted-example.toml` as described in our [getting-started](authority_public_key) guide.
> Hosted TP authority_public_key fix

- protocols/Cargo.lock
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/handlers/common.rs
- protocols/v2/roles-logic-sv2/src/handlers/job_declaration.rs
- protocols/v2/roles-logic-sv2/src/handlers/mining.rs
- protocols/v2/roles-logic-sv2/src/handlers/template_distribution.rs
- roles/Cargo.lock
- utils/Cargo.lock
- utils/message-generator/Cargo.lock
Each Sv2 protocol have a server and client trait. This trait have a method that handle serilaized messages. This PR add a method that handle deserilized messages, and modify the method for serilaized so that it just deserilize the message and call the new method. This can be usefull if we have more roles managed by the same rust process, to avoid some serailization and deserialization. It also bump the minor version of the roles-logic-sv2 lib cause it add a feature and do not breack and API.
> Add handlers for deserilized messages

- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/subprotocols/job-declaration/src/submit_solution.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
This PR fixes the way JDS manages and uses `version` field in the block header, taking it from the `successful share` instead of taking it from the `DeclareMiningJob` message.
Right now, since version-rolling is used, this field was changed many times by the miner and so JDS was not able to correctly build the right block header, as pointed out in the Template Provider logs as well:
`2024-02-29T17:45:55Z ERROR: ProcessNewBlock: AcceptBlock FAILED (high-hash, proof of work failed)`.
In the past we didn't figure out the exact reason of this message, because in the meantime block were propagated also from JDC. While testing PR #761 we forced JDC to not propagate it and the result was that we couldn't propagate valid blocks found because of the aforementioned reason.
Since I applied this …
> JDS block construction and propagation fix

- .github/workflows/release-libs.yaml
since `roles` crates are `lib`, it makes sense to have them on crates.io as well
> publish `roles` lib crates to `crates.io`

- .github/workflows/release-bin.yaml
I created a mock release on my fork as a demo of how the Github Actions from this PR work. You can find it at https://github.com/plebhash/stratum/releases/tag/v1.0.0
It contains binaries for all roles:
- `jd_client`
- `jd_server`
- `mining_proxy_sv2`
- `pool_sv2`
- `translator_sv2`
each role has binaries available for the following platforms:
- `x86_64-linux-gnu` (Linux)
- `x86_64-apple-darwin` (MacOS x86-64)
- `arm64-apple-darwin` (MacOS Apple Silicon)
The idea is to always add release notes with a changelog, which is basically a list of changes since the last release tag.
As company PRs, there's also https://github.com/stratum-mining/stratum/pull/766 and https://github.com/stratum-mining/stratum/pull/771
> refactor Release Bin action

- .github/workflows/release-libs.yaml
- roles/pool/Cargo.toml
- roles/roles-utils/rpc/Cargo.toml
close #810 
also fixes:
- `noise_sv` version dependency on `pool`
- missing version for `stratum-common` dependency on `rpc_sv2`
> fix `sv2_ffi` lib publishing

- .github/workflows/release-libs.yaml
- check-versioning-lib-release.sh
Every time we merge some PR from `dev` to `main`, we need to make sure every modified crate version is properly increased. Otherwise, we will mess up the dependency chain of whoever is fetching from crates.io
This PR:
- changes `release-libs.yaml` so that the `Release Libs` workflow is triggered every time a PR is created against `main`.
- introduces a shell script (`check-versioning-lib-release.sh`) that checks the diff between `main` and `dev` branches... if some lib crate has been changed but its version wasn't bumped, the CI will trigger an error and stop (here's an [example](https://github.com/plebhash/stratum/actions/runs/8530384769/job/23368058479?pr=47#step:3:15) on my fork)
- removes `roles` from being published to crates.io (it doesn't make sense until …
> `release-libs.yaml` automatically triggered on PRs to `main`

- .github/workflows/release-libs.yaml
- check-versioning-lib-release.sh
this PR is just to make `dev` branch up-to-date with `main` branch, so that we can start development against `dev`
after https://github.com/stratum-mining/stratum/pull/790 it was outdated
I tried to rebase it locally but couldn't push it
> make `dev` up-to-date with `main`

- roles/Cargo.lock
- roles/test-utils/mining-device/Cargo.toml
- roles/test-utils/mining-device/src/main.rs
- utils/key-utils/src/lib.rs
Add a nicer user interface to the sv2 cpuminer with help messages. Add noise to the cpuminer.
This is the output of  `cargo run -- --help`
```console
Usage: mining-device [OPTIONS] --address-pool <ADDRESS_POOL>
Options:
-p, --pubkey-pool <PUBKEY_POOL>    Pool pub key, when left empty the pool certificate is not checked
-i, --id-device <ID_DEVICE>        Sometimes used by the pool to identify the device
-a, --address-pool <ADDRESS_POOL>  Address of the pool in this format ip:port or domain:port
--handicap <HANDICAP>          This value is used to slow down the cpu miner, it rapresents the number of micro-seconds that are awaited between one hashes, default is 0 [default: 0]
-h, --help                         Print help
-V, --version                      Print version
```
> Improve sv2 cpuminer

- roles/mining-proxy/config-examples/proxy-config-example.toml
- roles/pool/config-examples/pool-config-local-tp-example.toml
- roles/translator/config-examples/tproxy-config-local-jdc-example.toml
- roles/translator/config-examples/tproxy-config-local-pool-example.toml
fixes #818 
Reopened because of merge conflict in #837
> config parameters not used for anything( reopened )

- roles/jd-client/src/args.rs
- roles/translator/src/args.rs
Fixed the issue raised in issue #695
Do the following:
- cd to `roles/jd-client`
- run `cargo run -- -c ~/no-such-file.toml`
> Add error for non-existent configuration file

- roles/translator/src/main.rs
This patch adds a panic with an error description when tproxy fails to load the config file for any reason. It helps greatly to spot errors in the configuration file.
> tproxy: panic when failed to load config

- .github/workflows/release-bin.yaml
> add ARM architecture support on release-bin.yaml

- CONTRIBUTING.md
- roles/Cargo.lock
fix https://github.com/stratum-mining/stratum/issues/870
> merge dev main

- roles/Cargo.lock
apparently https://github.com/stratum-mining/stratum/pull/871 still didn't fix `roles/Cargo.lock`
if we do (on an updated `dev` branch):
```
cd roles
cargo build
```
then `roles/Cargo.lock` changes state:
```
git status
On branch dev
Your branch is up to date with 'origin/dev'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   Cargo.lock
```
This issue has been going on for a while and is quite annoying because it keeps creating conflicts on history.
So now I just did:
```
git checkout -b fix-cargo-lock
git add Cargo.lock
git commit
git push plebhash fix-cargo-lock
```
hopefully this PR fixes this issue once and for all.
> fix `roles/Cargo.lock`

- examples/ping-pong-with-noise/Cargo.toml
- roles/Cargo.lock
- roles/jd-client/Cargo.toml
- roles/jd-server/Cargo.toml
- roles/mining-proxy/Cargo.toml
- roles/pool/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/roles-utils/network-helpers/src/lib.rs
- roles/roles-utils/network-helpers/src/noise_connection_async_std.rs
- roles/roles-utils/network-helpers/src/noise_connection_tokio.rs
- roles/test-utils/mining-device/Cargo.toml
- roles/translator/Cargo.toml
- utils/message-generator/Cargo.toml
Fix network helper panic if peer close connection
When the remote peer try to open an encrypted sv2 connection and then
immediatly close the tcp connection, the helper for async std and tokio
it panic, mostly of the time we don't want to panic in this situation.
This commit add an error for this case and return it.
> Fix network helper panic if peer close connection

- benches/Cargo.lock
- roles/jd-server/src/lib/mempool/error.rs
- roles/jd-server/src/lib/mempool/mod.rs
- roles/jd-server/src/main.rs
Closes #784 
- Removed the unnecessary use of tokio::task::spawn in update_mempool, leveraging the existing async function context for all operations.
- Removed the TokioJoin(JoinError) implementation since it is not been used
> Refractor update_mempool module in JDS mempool module for simplified async flow

- roles/test-utils/mining-device/src/main.rs
In order to calculte the hash rate of the machine in which is running the sv2 cpu miner was using a fster function that the one that use to actually mine. This commit change the function that the cpu miner use to calculte the hash rate using the same one that is used when it mine.
> Fix sv2 cpu miner hash rate calculation

- protocols/v2/codec-sv2/src/lib.rs
- protocols/v2/framing-sv2/src/framing2.rs
- protocols/v2/framing-sv2/src/header.rs
- protocols/v2/framing-sv2/src/lib.rs
adds Rust Docs for `framing_sv2`, as described in https://github.com/stratum-mining/stratum/issues/845
also renames `NoiseFrame` into `HandShakeFrame`
the documentation effort was guided by discussion with @Fi3 on https://github.com/stratum-mining/stratum/discussions/858
> docs `framing_sv2`

- benches/Cargo.lock
- common/Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- roles/Cargo.lock
- roles/jd-server/Cargo.toml
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/pool/Cargo.toml
- roles/pool/src/lib/mining_pool/mod.rs
- utils/Cargo.lock
- utils/key-utils/src/lib.rs
fixes issue raised in #749 
This was essentially a refactoring issue
> better import for libsecp256k1

- roles/translator/config-examples/tproxy-config-hosted-pool-example.toml
this PR is a companion to https://github.com/stratum-mining/stratumprotocol.org/pull/216
> add `tproxy-config-hosted-pool-example.toml` (`dev` branch)

- benches/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- roles/jd-client/Cargo.toml
- roles/translator/Cargo.toml
we forgot to bump the `framing_sv2` version on https://github.com/stratum-mining/stratum/pull/848
> bump `framing_sv2` version

- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/job_declarator/message_handler.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
This PR addresses the way `last_declare_mining_jobs_sent` are managed by JDC. 
Before this PR, we could end up in a situation in which we were not able to exit from the loop inside `on_set_new_prev_hash` function because of this line: https://github.com/stratum-mining/stratum/blob/0b131916f8bbc739a57b739c059fe887bc538931/roles/jd-client/src/lib/job_declarator/mod.rs#L362 
The situation occured every time a new job was created and declared right after the future job linked to the new prev_hash. Because of [this line](https://github.com/stratum-mining/stratum/blob/0b131916f8bbc739a57b739c059fe887bc538931/roles/jd-client/src/lib/job_declarator/mod.rs#L275) the second job (not future) was extracted in this scenario (instead of the right previous one, the future one). In this way the …
> Better management of LastDeclareJobs - no more wrong fallback-system activations

- protocols/v2/codec-sv2/Cargo.toml
while fixing `check-versioning-lib-release.sh` (https://github.com/stratum-mining/stratum/pull/926) and preparing for Release `v1.0.1` (https://github.com/stratum-mining/stratum/pull/925), I noticed we were forgetting to bump `codec_sv2` crate version, as a result of a patch applied to one of it's dependencies (`framing_sv2`) via https://github.com/stratum-mining/stratum/pull/913
`framing_sv2` (which is a dependency of `codec_sv2`) had it's `MINOR` version bumped, which means `codec_sv2` also needs to bump it's `MINOR` version
> bump codec sv2 version

- .github/workflows/release-bin.yaml
- RELEASE.md
I was trying to release the binary executables and I noticed there was a naming clash with the previous release.
https://github.com/stratum-mining/stratum/actions/runs/9258045890/job/25467603017#step:13:46
This PR is adjusting the `Release Bin` CI Job so that each output executable has the Global Release version as a substring.
That way, there will be no name clashing in the future.
It starts from the assumption that the `Release Bin` Job was triggered from a branch named `vMAJOR.MINOR.PATCH`, which is highlighted on the changes to `RELEASE.md`
> Specify version on filenames inside `Release Bin` CI

- .github/workflows/clippy-lint.yaml
- .github/workflows/fmt.yaml
- .github/workflows/run-and-track-benchmarks-on-main.yaml
- .github/workflows/sv2-header-check.yaml
- .github/workflows/test.yaml
This PR is addressing Node.js deprecation in Github Action workflow as shown below:
> update deprecated Node.js 16 

- benches/benches/src/sv1/lib/client.rs
- protocols/v1/src/lib.rs
- protocols/v1/src/methods/client_to_server.rs
- protocols/v1/src/methods/server_to_client.rs
This PR fixes 
`ERROR translator_sv2::lib::status: Error: V1Protocol(Method(ParsingMethodError((HexError(OddLength), StandardRequest(StandardRequest { id: 150166, method: "mining.subscribe", params: Array [String("bmminer/2.0.0"), String("265800001")] })))))`
errors.
I'm new to Rust and made this PR with the help of ChatGPT, so I'm not sure it's fully correct. Nevertheless, it fixes the actual error in my case.
This error happens when the miner sends an odd-sized extranonce.
> fix(translator): fix HexError(OddLength) in mining.subscribe handler

- protocols/v2/subprotocols/common-messages/src/setup_connection.rs
This PR fix a typo in `setup_connection.rs`
> Fix 'available' typo 

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
Make it easier to compare:
* Bitcoin target
* upstream target (if any)
* hash
The Bitcoin target was previously rendered as `{ head: 0, tail: ... }`, render it as hex instead.
Add spaces to align all three.
Before:
```
2024-06-07T18:01:37.745967Z DEBUG roles_logic_sv2::handlers::mining: Received SubmitSharesExtended message
2024-06-07T18:01:37.745979Z DEBUG roles_logic_sv2::channel_logic::channel_factory: Checking target for share Extended(SubmitSharesExtended { channel_id: 1, sequence_number: 0, job_id: 1, nonce: 2355753102, ntime: 1717783221, version: 757661696, extranonce: Owned([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]) })
2024-06-07T18:01:37.746007Z DEBUG roles_logic_sv2::channel_logic::channel_factory: Bitcoin target: Target { head: 0, tail: 2409966232598499819520 } …
```
> Log Bitcoin target as hex, align targets

- protocols/v2/roles-logic-sv2/src/parsers.rs
...to `TryFrom<(u8, &'a mut [u8])> for PoolMessages`
resolves #936
> Add missing `TemplateDistributionTypes` case

- roles/jd-client/src/main.rs
> Handle `jd-client` config error

- protocols/v2/subprotocols/job-declaration/src/submit_solution.rs
> fix `GetSize` for `SubmitSolutionJd`

- utils/message-generator/src/parser/sv2_messages.rs
> MG understands `SubmitSolution` as a valid JD message

- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/job_declarator/message_handler.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
- roles/jd-client/src/lib/mod.rs
- roles/jd-client/src/main.rs
The PR is opened to address the suggested changes by @Fi3 on PR #904. The comments are as follows:
- [Better management of LastDeclareJobs - no more wrong fallback-system activations #904 (comment)](https://github.com/stratum-mining/stratum/pull/904#discussion_r1609437598): Panic in safe lock state not advisable.
- [Better management of LastDeclareJobs - no more wrong fallback-system activations #904 (comment)](https://github.com/stratum-mining/stratum/pull/904#discussion_r1609469048): We are now using an array of size 2, as there should not be more than 2 Request id with corresponding jobs at any given point. If an anomaly arises, the process will error out.
> Redefining lastDeclareJob 

- roles/translator/src/lib/downstream_sv1/diff_management.rs
I think as long as #988 is not fixed, there is no point in leaving this test on.
Its currently producing too much false alarms which can block new pull requests as well as make it harder to find issues in new pull requests.
> Ignore `test_diff_management` test

- .github/workflows/rust-msrv.yaml
- protocols/Cargo.toml
- roles/Cargo.toml
- rust-toolchain.toml
- utils/Cargo.toml
> Add MSRV 1.75 workflow check

- utils/message-generator/src/executor.rs
- utils/message-generator/src/main.rs
- utils/message-generator/src/parser/actions.rs
close #1023 and unblock #1025 
this allows for MG to verify that a connection was not closed
it also refactors some parts of `Executor::execute` by moving some logic to the arms of `match result`, which improves code readability
> add `ActionResult::SustainConnection` to MG

- .github/workflows/mg.yaml
Github only allows branch protection rules based on specific CI jobs. So we are adding a new job that just takes all the other MG test jobs as a prerequisite, so we can use this as an umbrella rule for branch protection.
when some MG test fails:
when all MG tests pass:
> add `Aggregate MG Test Results` job to MG CI 

- roles/mining-proxy/src/lib/downstream_mining.rs
- roles/mining-proxy/src/lib/upstream_mining.rs
- roles/mining-proxy/src/main.rs
Add graceful shutdown for mining proxy fixing #484 
PS: I'm not sure if I should merge against dev or main
> Graceful shutdown for mining-proxy

- .github/workflows/mg.yaml
- roles/jd-server/src/lib/job_declarator/mod.rs
- test/config/jds-receive-solution-while-processing-declared-job/jds-config.toml
- test/message-generator/mock/jdc-mock-jds-receive-solution-while-processing-declared-job.json
- test/message-generator/test/jds-receive-solution-while-processing-declared-job/jds-receive-solution-while-processing-declared-job.json
- test/message-generator/test/jds-receive-solution-while-processing-declared-job/jds-receive-solution-while-processing-declared-job.sh
this PR:
- fixes the bug described in #912
- adds a MG test to assert the correct JDS behavior under those specific conditions
> avoid JDS dropping connection on `SubmitSolution` with missing txs 

- roles/translator/src/lib/downstream_sv1/diff_management.rs
we made some adjustments to `test_diff_management` via #995 , which unfortunately did not fully fix #988 
both @Fi3 and I did some investigation on this:
- https://github.com/stratum-mining/stratum/pull/995#issuecomment-2209602801
- https://github.com/stratum-mining/stratum/issues/988#issuecomment-2250316209
in summary, bigger values for `total_run_time` seems to always improve things, so this PR adjusts it to 60s in hope it will fix this once and for all
if we have to re-open #988 again after this is merged, then we should consider #1074 , which completely disables `test_diff_management` until a more sustainable fix is found
> `test_diff_management`: adjust `total_run_time` to  60s

- roles/jd-client/src/lib/mod.rs
fix #1079 
this PR simply reorders the sequence between `upstream_sv2::Upstream::parse_incoming` and `upstream_sv2::Upstream::setup_connection` inside `JobDeclaratorClient::initialize_jd` 
`Upstream::parse_incoming` only calls `handle_message_mining`, which is not able to handle a `SetupConnection.Success` (because it belongs to the "Common Messages" category, not "Mining Messages")
> JDC parse incoming mining messages from upstream after SetupConnection

- protocols/v2/binary-sv2/serde-sv2/Cargo.toml
- protocols/v2/binary-sv2/serde-sv2/src/lib.rs
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/codec-sv2/src/lib.rs
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/const-sv2/src/lib.rs
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/framing-sv2/src/lib.rs
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/common-messages/src/lib.rs
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/job-declaration/src/lib.rs
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/mining/src/lib.rs
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/subprotocols/template-distribution/src/lib.rs
Many of the low level libs under `protocols` are `no_std`. That is great, since it allows for potential firmware integrations using `rust-embedded` and targets without MMUs (e.g.: Xtensa ESP32, ARM Cortex-M, etc).
Some projects in the community even have some potential to leverage SRI `protocols` crates for firmware integration, e.g.: https://github.com/bitaxeorg/esp-miner-rs
However, for most common deployment scenarios (e.g.: x86-64), high level application code (e.g.: `roles`) has no hard requirement for `no_std`. Also, having it as a mandatory feature becomes a blocker to many desirable changes.
> make `no_std` into an optional feature on `protocols` crates

- protocols/Cargo.lock
- protocols/v2/binary-sv2/serde-sv2/Cargo.toml
- protocols/v2/binary-sv2/serde-sv2/src/primitives/sequences/seq0255.rs
required to unblock https://github.com/stratum-mining/stratum/pull/985#issuecomment-2234328927
> add missing `impl` for `Seq0255` on `binary_sv2/serde-sv2`

- protocols/Cargo.lock
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/subprotocols/template-distribution/src/new_template.rs
- protocols/v2/sv2-ffi/Cargo.toml
this PR is a requirement to unblock https://github.com/stratum-mining/stratum/pull/985#issuecomment-2234328927
it needs https://github.com/stratum-mining/stratum/pull/932 to be merged first
> import `TryInto` on `template_distribution_sv2`

- benches/Cargo.toml
- protocols/Cargo.lock
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/codec-sv2/src/lib.rs
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- roles/Cargo.lock
- roles/jd-client/Cargo.toml
- roles/jd-server/Cargo.toml
- roles/mining-proxy/Cargo.toml
- roles/pool/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/test-utils/mining-device/Cargo.toml
- roles/translator/Cargo.toml
- utils/message-generator/Cargo.toml
after merging https://github.com/stratum-mining/stratum/pull/976 we didn't properly manage versioning of `framing_sv2` + `codec_sv2` crates
this PR fixes this
hopefully this will not happen again once https://github.com/stratum-mining/stratum/pull/985 is finally merged, as it will enforce semver on both `dev` and `main` branches
> bump protocols versioning

- protocols/Cargo.lock
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
follow up to https://github.com/stratum-mining/stratum/pull/1084, where I missed `common_messages_sv2`
> bump `common_messages_sv2` version

- .github/workflows/semver-check.yaml
> Add semver check workflow yaml

- roles/translator/Cargo.toml
- roles/translator/src/lib/downstream_sv1/downstream.rs
- roles/translator/src/lib/proxy/bridge.rs
- roles/translator/src/lib/status.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
- roles/translator/src/main.rs
When the jdc changes upstream, it disconnects the TProxy.
This PR addresses this issue by making the TProxy reconnecting to the JDC.
Removed the part related to the MG test.
How to test this PR:
The idea is to have a pool that rejects a share. It is possible to do that by tweaking the part of the code needed to check the target, forcing the pool to calculate a wrong hash for a share. 
Following @GitGab19 [suggestion](https://github.com/stratum-mining/stratum/issues/844#issuecomment-2118864024), the part of the code responsible for that is  [`roles-logc-sv2::channel_logic::channel_factory::on_submit_shares_extended(...)`](https://github.com/stratum-mining/stratum/blob/dev/protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs#L1146). Since other roles check the share using the …
> Translator restart if disconnected from upstream

- .github/workflows/semver-check.yaml
the `framing_sv2/with_serde` flag [was added](https://github.com/stratum-mining/stratum/commit/100a331a3bcda0721835ac4f5ca17c8554df79ef) to `roles_logic_sv2` aiming to unblock the SemVer CI introduced via https://github.com/stratum-mining/stratum/pull/985
unfortunately the `with_serde` feature flag is broken for `framing_sv2`, and that is having undesired consequences on downstream crates that use `roles_logic_sv2` as dependencies
this PR allows us to can keep our SemVer CI unblocked by this problem, so that via https://github.com/stratum-mining/stratum/pull/1101 we can make sure that `roles_logic_sv2` does not include `framing_sv2/with_serde`
> bypass `cargo semver-checks --all-features` for roles_logic_sv2

- protocols/Cargo.lock
- protocols/v2/roles-logic-sv2/Cargo.toml
this `framing_sv2/with_serde` flag was added to `roles_logic_sv2` aiming to unblock the SemVer CI introduced via https://github.com/stratum-mining/stratum/pull/985
unfortunately the `with_serde` feature flag is broken for `framing_sv2`, and that is having undesired consequences on downstream crates that use `roles_logic_sv2` as dependencies
via https://github.com/stratum-mining/stratum/pull/1100 we can keep our SemVer CI unblocked by this problem, but we also need to make sure `roles_logic_sv2` does not include `framing_sv2/with_serde`
this PR is patching `roles_logic_sv2` to achieve this goal
> patch `roles_logic_sv2` `with_serde` flag

- .github/workflows/semver-check.yaml
`cargo semver-checks` had a new release a couple hours ago: https://github.com/obi1kenobi/cargo-semver-checks/releases/tag/v0.34.0
this release changed MSRV of `cargo semver-checks` from `1.75` to `1.77`
currently, `semver-check.yaml` is installing `1.75`:
https://github.com/stratum-mining/stratum/blob/a09084426092a6dfef8862571bc4a0098a05e935/.github/workflows/semver-check.yaml#L21-L25
as a consequence, our entire SemVer CI is failing with:
```
Run cargo semver-checks
error: rustc version is not high enough: >=1.77.0 needed, got 1.75.0
HELP: to use the latest rustc, run `rustup update stable && cargo +stable semver-checks <args>`
```
[example](https://github.com/stratum-mining/stratum/actions/runs/10396114294/job/28789511722?pr=1102)
this PR changes `1.75` to `stable` on …
> use rust stable for semver CI

- benches/Cargo.lock
- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/template_receiver/mod.rs
If the JDC switches to solo_mining, then it initializes as solo mining (using `initialize_jd_as_solo_miner`).
This function initialize a `DownstreamMiningNode` with `jd` field set to `None`. This is the right behaviour, but makes panic this [unwrap](https://github.com/stratum-mining/stratum/blob/dev/roles/jd-client/src/lib/downstream.rs#L379).
Since we are doing solo mining, it should be care of the downstream to change the coinbase downstream, instead of wrapping a None, the `coinbase_tx_prefix` and `suffix` are ignored. 
Perhaps this is not the best way to do that, feedback needed.
In the commit message is writtend how to test this PR.
This PR  is on top of [PR1001](https://github.com/stratum-mining/stratum/pull/1001).
This PR closes [issue …
> Fix JDC fallback to solo-mining

- protocols/Cargo.lock
- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/codec/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/lib.rs
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/src/lib.rs
- roles/Cargo.lock
In no-serde-sv2 an sv2 sequence is generic over T. If we want this sequence to be Deserialize we need T to be Fixed and GerMarker. This 2 traits were private since all the sv2 types are already defined in no-serde-sv2. But if we want to use sv2 types defined in an sv2 extensions we need to make these traits public.
The Encodable dervive macro in derive_codec implement GetSize for the passed struct. But GetSize is also a blanket implementation for every type that implement Fixed. So if we implement Fixed for our new sv2 type and then we derive Encodable (commonly renamed Serialize) we get an error. This commit add an attribute to Encodable called already_sized if the struct that we want derive Encodable is market as already_sized the macro will not implement GetSize for it.
This commit …
> Add support for data types defined by sv2 extensions

- protocols/Cargo.lock
- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/codec/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/lib.rs
In order to implement Encodable (aka Serialize) for sv2 type defined by extensions EncodablePrimitive is needed.
> Update binary-sv2/no-serde-sv2 excport EncodablePrimitive

- RELEASE.md
and maintain only `main` without `dev` branch.
relates to #1098
> Consider using release branches

- .github/workflows/release-libs.yaml
> stop publishing some crates

- .github/workflows/auto-rebase.yaml
The goal of this PR is to better manage the situation in which every time we merge a PR against `main`, all the others become outdated, and we need to ask PR authors to rebase them. 
- This creates a bottleneck when we have more PRs ready to be merged all together, but instead we need to wait for authors to rebase and force-push. 
- We could update them by using the "Update branch" button, but that's not ideal since the authors's commits will be committed by the maintainer who updates the PR, leading to track the authors commits as "co-authored" by mainainer as well. 
- We could also update the PRs by merging `main` into PR's branch, but that's not ideal since we would add a merge commit only for this, which will be tracked in the git history forever.
This PR adds a new workflow file …
> Auto rebase workflow addition

- .github/workflows/release-libs.yaml
currently, `release-libs.yaml` will publish the libs to `crates.io` every time we merge to `main`, which is the main event for releases
with the new conventions proposed in #1124, we want to avoid that, since not every merge to `main` will be a release
this PR makes `release-libs.yaml` only be able to run:
- once new release tags are added
- via manual trigger
> publish libs to `crates.io` on release tags

- RELEASE.md
formalizing @GitGab19 's proposal: https://github.com/stratum-mining/stratum/issues/1141#issuecomment-2312362812
> global release docs

- roles/translator/src/lib/downstream_sv1/diff_management.rs
after some failed attempts on #995, this PR disables the `test_diff_management` unit test as a temporary fix to #988
we should not close #988 until a more sustainable fix is found for the long term
we should also be extra careful when modifying `roles/translator/src/lib/downstream_sv1/diff_management.rs`
> ignore `test_diff_management`

- .github/workflows/run-benchmarks.yaml
- .github/workflows/track-benchmarks.yaml
- benches/benches/src/sv1/criterion_sv1_benchmark.rs
- benches/benches/src/sv2/criterion_sv2_benchmark.rs
This PR updates the way branches are managed by [bencher](bencher.dev), greatly improving the possibility of getting false alarms (about performance regressions) by our CI. 
Close #1051
> Fix bencher false alarms on CI

- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/tests/common/mod.rs
> Add Template Provider to integration test project

- .github/workflows/sv2-header-check.yaml
follow up to https://github.com/stratum-mining/stratum/pull/1170
`cbindgen` v0.21.0 cannot be built with Rust v1.75.0
> use 1.75.0 toolchain on sv2-header-check.yaml

- roles/tests-integration/tests/common/mod.rs
> use fixed `temp_dir` for TP on integration tests

- protocols/v2/const-sv2/README.md
- protocols/v2/const-sv2/src/lib.rs
- protocols/v2/sv2-ffi/sv2.h
This PR adds rust docs to `const_sv2` crate.
For now it contains a set of comments, which will be resolved after discussions at https://github.com/stratum-mining/stratum/discussions/1159
Closes #1016
> Rust docs for `protocols::v2::const-sv2`

- roles/pool/src/lib/mining_pool/mod.rs
this is breaking compilation of SRI pool with `test_only_allow_unencrypted` compilation
> fix `network_helpers_sv2` import on `mining_pool` mod

- roles/test-utils/mining-device/README.md
- roles/test-utils/mining-device/src/lib/mod.rs
- roles/test-utils/mining-device/src/main.rs
close #1188
- introduces a mechanism for advertising a custom nominal hashrate (by multiplying measured hashrate with a constant)
- fixes `measure_hashrate` so it also takes `handicap` into consideration (otherwise `measure_hashrate` will return something that doesn't reflect what will happen during the actual mining when `handicap` is used)
- makes sure we use all available parallelism (there were some weird subtractions that didn't seem to make sense cc @Fi3)
> add `--nominal-hashrate-multiplier` to `mining-device`

- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/const-sv2/README.md
This PR adds new badges, complying `const_sv2` README.md to [docs standards](https://github.com/stratum-mining/stratum/discussions/970#discussioncomment-10765850)
> `const_sv2` - README update to comply with docs standards

- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/error.rs
- roles/jd-client/src/lib/proxy_config.rs
- roles/jd-client/src/lib/upstream_sv2/mod.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
- roles/mining-proxy/src/lib/error.rs
- roles/translator/src/lib/mod.rs
- roles/translator/src/lib/proxy/bridge.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
> fix cargo warnings in roles

- common/Cargo.toml
- protocols/v1/Cargo.toml
- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/codec/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/Cargo.toml
- protocols/v2/binary-sv2/serde-sv2/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/roles-utils/rpc/Cargo.toml
- utils/bip32-key-derivation/Cargo.toml
- utils/buffer/Cargo.toml
- utils/error-handling/Cargo.toml
- utils/key-utils/Cargo.toml
This PR enables the  `all-feature` flag for `rust-docs` in every published crate.
Close #1210
> Enable `all-feature` flag for rust-docs

- RELEASE.md
as discussed on the dev call today (10/15/24), we're going to continue leveraging the automated generation of release notes and manually add extra contextual information to each release page as needed
this PR removes `CHANGELOG.MD` and adapts `RELEASE.md` accordingly.
> update release process

- protocols/v1/Cargo.toml
- roles/Cargo.lock
@Fi3 in #1149 raised issue with pretty_env_logger, importing triggered a vulnerability, and contributors in the discussion suggested to remove the dependency. 
This PR removes it. Deleted from Cargo.lock in v1 folder. 
Compiles and passes tests. `cargo test -p sv1_api'
> remove pretty_env_logger as dependency

- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- roles/Cargo.lock
> bump crates versions for docs on release v1.1.0

- roles/tests-integration/tests/common/mod.rs
> Dont provie TP pubkey in test env

- protocols/v2/const-sv2/Cargo.toml
- roles/Cargo.lock
const_sv2 does depend on secp256k1 anymore
> const_sv2: remove unused dep (secp256k1)

- roles/tests-integration/tests/common/sniffer.rs
- roles/tests-integration/tests/pool_integration.rs
> Fix ambiguous naming on Integration Tests Sniffer API (`next_upstream_message` vs `next_downstream_message`)

- .github/workflows/track-benchmarks.yaml
This changeset updates the Bencher CLI to the new recommended usage.
- Update deprecated CLI options: https://bencher.dev/docs/explanation/branch-selection/
- Safer and more succinct tracking from forks: https://bencher.dev/docs/how-to/github-actions/#pull-requests-from-forks
> Update Bencher CLI usage

- roles/jd-server/config-examples/jds-config-local-example.toml
- roles/jd-server/src/lib/job_declarator/message_handler.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/jd-server/src/lib/mempool/mod.rs
> Fix missing transaction in light mempool bug

- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/binary-sv2/README.md
- protocols/v2/binary-sv2/binary-sv2/src/lib.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/README.md
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/codec/decodable.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/codec/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/copy_data_types.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/inner.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/seq_inner.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/lib.rs
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/README.md
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/src/lib.rs
- protocols/v2/binary-sv2/serde-sv2/Cargo.toml
- protocols/v2/binary-sv2/serde-sv2/README.md
- protocols/v2/binary-sv2/serde-sv2/src/lib.rs
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/const-sv2/README.md
- protocols/v2/const-sv2/src/lib.rs
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/framing-sv2/README.md
- protocols/v2/framing-sv2/src/lib.rs
- utils/buffer/src/buffer_pool/mod.rs
- utils/buffer/src/lib.rs
Most of protocol/v2 crates are almost `no_std`, as listed [here](https://github.com/stratum-mining/stratum/issues/1130#issuecomment-2438642786).
Having a lib crate that can be `no_std` or `std` by the selection of a feature :
```rust
#![cfg_attr(not(feature = "std"), no_std)]
```
or the current implementation :
```rust
#![cfg_attr(feature = "no_std", no_std)]
```
is only usefull if :
- the crate could use some `std` related dependency (for instance `std::vec::Vec`)
- but we want the crate's user to be able to not have a dependancy on `std` so we disable the functionalities using `std`
In some case we can replace the `std` dep by its `alloc` equivalent if exists (`alloc::vec::Vec`) and we can keep the functionality in `no_std` environement.
Finally, a `std` binary can use some `no_std` …
> enforce `no_std` for all? protocol/v2 crates

- roles/Cargo.lock
- roles/jd-client/src/lib/proxy_config.rs
- roles/tests-integration/Cargo.toml
- roles/tests-integration/tests/common/mod.rs
> Add JDC/S initializers in integration tests

- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/tests/common/mod.rs
> Add `tproxy` initializer for Integration Tests

- roles/tests-integration/tests/common/mod.rs
- roles/tests-integration/tests/common/sniffer.rs
- roles/tests-integration/tests/pool_integration.rs
> `Sniffer` Improvements

- roles/jd-client/config-examples/jdc-config-hosted-example.toml
- roles/pool/config-examples/pool-config-hosted-tp-example.toml
During latest changes on our hosted infrastructure, we had to spin up a new TP for `testnet4`, so a new `sv2_authority_key` has been generated there.
This PR updates Pool and JDC to use the newest public key on their relative config examples.
> `tp_authority_public_key` update in pool & jdc configs

- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/common-messages/README.md
- protocols/v2/subprotocols/common-messages/src/channel_endpoint_changed.rs
- protocols/v2/subprotocols/common-messages/src/lib.rs
- protocols/v2/subprotocols/common-messages/src/setup_connection.rs
- protocols/v2/sv2-ffi/sv2.h
resolves https://github.com/stratum-mining/stratum/issues/1203
> `common_messages_sv2` docs

- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/subprotocols/template-distribution/README.md
- protocols/v2/subprotocols/template-distribution/src/coinbase_output_data_size.rs
- protocols/v2/subprotocols/template-distribution/src/lib.rs
- protocols/v2/subprotocols/template-distribution/src/new_template.rs
- protocols/v2/subprotocols/template-distribution/src/request_transaction_data.rs
- protocols/v2/subprotocols/template-distribution/src/set_new_prev_hash.rs
- protocols/v2/subprotocols/template-distribution/src/submit_solution.rs
- protocols/v2/sv2-ffi/sv2.h
> Docs for Template Distribution Messages

- protocols/v2/binary-sv2/binary-sv2/README.md
- protocols/v2/binary-sv2/binary-sv2/examples/encode_decode.rs
- protocols/v2/binary-sv2/binary-sv2/src/lib.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/README.md
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/codec/decodable.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/codec/encodable.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/codec/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/copy_data_types.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/inner.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/seq_inner.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/lib.rs
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/README.md
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/src/lib.rs
- protocols/v2/sv2-ffi/sv2.h
> doc binary-sv2

- roles/Cargo.lock
- roles/jd-client/Cargo.toml
- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
motivated by #1280
good to have, but doesn't close the #1280 yet
> Minor warning and error grammar and typo fixes

- roles/tests-integration/tests/common/mod.rs
replace https://github.com/stratum-mining/stratum/pull/1290
close https://github.com/stratum-mining/stratum/issues/1288
---
`BitcoinD` already [implements the `Drop` trait](https://docs.rs/bitcoind/latest/bitcoind/struct.BitcoinD.html#impl-Drop-for-BitcoinD)
then we have a second `Drop` implementation for `TemplateProvider`:
https://github.com/stratum-mining/stratum/blob/5bcd54d6eee28a55fcc20c2aaaa707e659cf2136/roles/tests-integration/tests/common/mod.rs#L167-L171
this is not only redundant, but likely the root cause of our problems here, since it calls RPC `stop` 2x:
- the first one kills the process
- the second one fails, since the process is already dead
> remove redundant `Drop` implementation from ITF `TemplateProvider`

- roles/tests-integration/tests/common/mod.rs
- roles/tests-integration/tests/translator_integration.rs
> Duplicate tproxy MG test in integration tests

- .github/workflows/test.yaml
closes #1278 
The error Permission denied (os error 13) indicates that your process does not have the necessary permissions to execute the bitcoind binary located at /tmp/.template-provider/bitcoin-sv2-tp-0.1.9/bin/bitcoind
Solution: changing macos runner version worked
> add unix specific execution permission to tp binary executable

- roles/jd-server/config-examples/jds-config-local-example.toml
Otherwise Bitcoin Core `-debug=rpc` logging becomes too noisy.
It's probably also too high for production on mainnet, "distracting" the node from its other work, but that's something that benchmarking might find.
> Have JDS ping local mempool less frequently

- .github/workflows/semver-check.yaml
- benches/Cargo.toml
- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/serde-sv2/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- roles/Cargo.lock
- roles/jd-client/Cargo.toml
- roles/jd-server/Cargo.toml
- roles/mining-proxy/Cargo.toml
- roles/pool/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/test-utils/mining-device/Cargo.toml
- roles/translator/Cargo.toml
- utils/message-generator/Cargo.toml
follow up to #1276 according to this comment: https://github.com/stratum-mining/stratum/issues/1275#issuecomment-2532472582
---
we are planning to remove more cargo build features in the future, and therefore it's desirable to enforce semver around this via CI
as a consequence, we need to use `cargo semver-check` v0.37 (or greater, but always locked)
this creates incompatibilities with MSRV, therefore we need to run `cargo semver-check` on `stable`
finally, switching `cargo semver-check` to v0.37 forced us to bump many crate versions
---
PR changes:
- use `cargo semver-check` v0.37
- use `stable` toolchain instead of MSRV 1.75
- bump MAJOR for crates that dropped `no_std` features on #1276 
- bump PATCH for crates that had dependencies on the crates that were bumped because of #1276
> use `cargo semver-checks` v0.37 and bump crate versions as a follow-up to #1276

- .github/workflows/test.yaml
Recent changes to `macos-14` still use the latest macOS 14 runner. This PR aims to switch the macOS runner to version 13 to resolve the 'permission denied' error on macOS.
> change macos-14 to macos-13

- roles/Cargo.lock
- utils/Cargo.lock
- utils/buffer/Cargo.toml
we need to bump `buffer_sv2` PATCH version for two modifications introduced during milestone v1.2.0:
- #1230
- #1232
this PR bumps `buffer_sv2` PATCH from 1.1.0 to 1.1.1
> bump `buffer_sv2` patch

- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/framing-sv2/README.md
- protocols/v2/framing-sv2/examples/sv2_frame.rs
- protocols/v2/framing-sv2/src/error.rs
- protocols/v2/framing-sv2/src/framing.rs
- protocols/v2/framing-sv2/src/header.rs
- protocols/v2/framing-sv2/src/lib.rs
> `framing-sv2` doc cmts to conform to standard

- roles/Cargo.lock
- roles/test-utils/mining-device-sv1/Cargo.toml
- roles/test-utils/mining-device-sv1/src/client.rs
- roles/test-utils/mining-device-sv1/src/main.rs
- roles/test-utils/mining-device-sv1/src/miner.rs
Update mining-device-sv1 from println! to info! using tracing following mining-device as example.
the issue: https://github.com/stratum-mining/stratum/issues/1286
> feat: update println! and eprintln! to info using tracing cargo.

- roles/tests-integration/tests/common/mod.rs
- roles/tests-integration/tests/pool_integration.rs
It's had enough manual testing that I feel good about this release. Let's make sure there's breaking changes I missed though.
> Bump TP to 0.1.13 for CI

- benches/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/common-messages/README.md
- protocols/v2/subprotocols/common-messages/src/lib.rs
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/job-declaration/README.md
- protocols/v2/subprotocols/job-declaration/src/lib.rs
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/mining/README.md
- protocols/v2/subprotocols/mining/src/lib.rs
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/subprotocols/template-distribution/README.md
- protocols/v2/subprotocols/template-distribution/src/lib.rs
- protocols/v2/subprotocols/template-distribution/src/new_template.rs
- protocols/v2/sv2-ffi/Cargo.toml
- roles/Cargo.lock
`common_messages_sv2` `job_declaration_sv2` `mining_sv2` `template_distribution_sv2`: remove the `no_std` feature and make them `#![no_std]` as they never use `std` anywhere.
- bump their MAJOR version because of feature removal
- bump the dependant crates PATCH version
- updates docs
> `subprotocol` crates `no_std` support

- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
> remove `readme` field from `Cargo.toml` of crates that dont have a `README.md`

- .github/workflows/release-libs.yaml
- scripts/release-libs.sh
close #1327 
this PR adds a new `scripts/release-libs.sh`, which is used to publish each crate to `crates.io`
the script returns `0` on success of `cargo publish`, and `1` on failure
the only exception is when `cargo publish` fails because the crate is already published
in that case, the script also returns `0`
> add `scripts/release-libs.sh`

- .github/workflows/release-libs.yaml
follow up to https://github.com/stratum-mining/stratum/pull/1329
it turns out that `cargo` v1.83.0 (which is the current `stable` toolchain) outputs the following string when `cargo publish` is trying to publish a crate that has already been published:
```
$ cargo +stable publish
Updating crates.io index
error: crate stratum-common@1.0.0 already exists on crates.io index
```
but the script checks for a different string, which is the output of `cargo` v1.75.0 (MSRV):
```
$ cargo +1.75.0 publish
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error (status 400 Bad Request): crate version `1.0.0` is already uploaded
```
one could argue:
> why not adapt `scripts/release-libs.sh` to look for the `already exists on crates.io index` …
> `release-libs.yaml` use `1.75.0` toolchain

- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/codec/Cargo.toml
- protocols/v2/binary-sv2/no-serde-sv2/derive_codec/Cargo.toml
- protocols/v2/binary-sv2/serde-sv2/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- utils/buffer/Cargo.toml
currently we are making sure all published `protocols` crates cover all of the crates features on Rust Docs
we enforce that by having the following on `Cargo.toml` of each crate:
```toml
[package.metadata.docs.rs]
all-features = true
```
this strategy was suggested on #1210 and implemented via #1211
during some discussions in #1311 @jbesraa pointed out that this strategy is a bit overengineered
I agree `all-features` is more generalistic than necessary, and it is causing trouble (e.g.: trying to build `cargo b --all-features` on `template_distribution_sv2` breaks due to `with_serde` and `prop_test` being built together)
also, features like `no_std` and `with_serde` are being deprecated, so there's no point in wasting engineering effort on them
---
this PR is simplifying the …
> simplify `[package.metadata.docs.rs]` on `protocols` crates

- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/job_creator.rs
- roles/Cargo.lock
- roles/tests-integration/tests/common/mod.rs
- roles/tests-integration/tests/pool_integration.rs
- roles/tests-integration/tests/translator_integration.rs
This PR introduces a new `last_ntime` field into `JobsCreators` struct to save the last `nTime` value sent by TP. 
In this way, the correct value is always used when creating new jobs (future and not), instead of using the current system time.
Closes #1324
> Fix timestamp bug - `min_ntime` becomes always the one sent by TP

- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/noise-sv2/README.md
- protocols/v2/noise-sv2/examples/handshake.rs
- protocols/v2/noise-sv2/src/cipher_state.rs
- protocols/v2/noise-sv2/src/error.rs
- protocols/v2/noise-sv2/src/handshake.rs
- protocols/v2/noise-sv2/src/initiator.rs
- protocols/v2/noise-sv2/src/lib.rs
- protocols/v2/noise-sv2/src/responder.rs
- protocols/v2/noise-sv2/src/signature_message.rs
- protocols/v2/noise-sv2/src/test.rs
Following @rrybarczyk [comment](https://github.com/stratum-mining/stratum/issues/1130#issuecomment-2422975674) on #1130.
Some equivalent conversion have been done (does not change any functionality, just using the `no_std` equivalents) :
- std::ptr -> core::ptr
- std::boxed::Box -> alloc::boxed::Box
- std::vec::Vec -> alloc::vec::Vec
- std::string::{String, ToString} -> alloc::string::{String, ToString}
- std::convert::TryInto -> core::convert::TryInto
- std::fmt::{Debug, Formatter, Result} -> core::fmt::{Debug, Formatter, Result}
- std::time::Duration -> core::time::Duration
To have a `no-std` version, the `--no-default-features` must be used.
Current public API (`std` dependant) is unchanged.
Additional public API for `no_std` compliance is available using the `*_with_rng` and …
> Propose an implementation of `noise_sv2` with optional `no_std`

- roles/jd-client/src/lib/mod.rs
closes: https://github.com/stratum-mining/stratum/issues/1266
This PR introduces several key changes to the `JobDeclaratorClient` implementation to enhance its functionality, improve shutdown handling, and resolve blocking issues during task execution:  
1. **Use of `tokio::spawn` for Task Initialization**  
- The `initialize_jd` and `initialize_jd_as_solo_miner` methods are now executed using `tokio::spawn`.  
- Previously, these methods were directly awaited in the event loop, causing blocking issues on disconnection events. By spawning these tasks, we ensure the event loop remains responsive.  
2. **Refactored Method Signatures**  
- Adjusted the signatures of `initialize_jd` and `initialize_jd_as_solo_miner` to accept `ProxyConfig` as a parameter instead of relying on `&self`.  
- …
> fix jdc sigterm signalling issue

- roles/translator/src/lib/mod.rs
Partially closes: #1266
The issue lies with the blocking nature of `self.internal_start().await` inside the loop. Since the .await suspends the current task, it prevents the tokio::select! from responding promptly to other events, such as the ctrl_c() signal. This PR tends to spawn to internal_start as a separate task, while still keeping the select! macro active to listen for other events.
> fix sigterm issue with translator sv2

- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/README.md
- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- protocols/v2/roles-logic-sv2/src/channel_logic/mod.rs
- protocols/v2/roles-logic-sv2/src/channel_logic/proxy_group_channel.rs
- protocols/v2/roles-logic-sv2/src/common_properties.rs
- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/handlers/common.rs
- protocols/v2/roles-logic-sv2/src/handlers/job_declaration.rs
- protocols/v2/roles-logic-sv2/src/handlers/mining.rs
- protocols/v2/roles-logic-sv2/src/handlers/mod.rs
- protocols/v2/roles-logic-sv2/src/handlers/template_distribution.rs
- protocols/v2/roles-logic-sv2/src/job_creator.rs
- protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
- protocols/v2/roles-logic-sv2/src/lib.rs
- protocols/v2/roles-logic-sv2/src/parsers.rs
- protocols/v2/roles-logic-sv2/src/routing_logic.rs
- protocols/v2/roles-logic-sv2/src/selectors.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
close https://github.com/stratum-mining/stratum/issues/1014
> docs `roles_logic_sv2`

- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/pool_integration.rs
- roles/tests-integration/tests/sniffer_integration.rs
> `Sniffer` messages cleaner

- protocols/v2/binary-sv2/no-serde-sv2/codec/src/codec/mod.rs
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/mod.rs
- protocols/v2/binary-sv2/serde-sv2/src/de.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/mod.rs
- protocols/v2/noise-sv2/src/cipher_state.rs
- protocols/v2/noise-sv2/src/handshake.rs
- protocols/v2/noise-sv2/src/signature_message.rs
- protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/sv2-ffi/src/lib.rs
- roles/roles-utils/rpc/src/lib.rs
resolves #1096  and #1048 
None of the dead code is removed and only marked with `dead_code` macro.
> Handle `cargo build` warnings

- examples/ping-pong-with-noise/Cargo.toml
- examples/template-provider-test/Cargo.toml
- protocols/fuzz-tests/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/codec-sv2/README.md
- protocols/v2/codec-sv2/examples/encrypted.rs
- protocols/v2/codec-sv2/src/lib.rs
- protocols/v2/sv2-ffi/Cargo.toml
- roles/Cargo.lock
- roles/jd-client/Cargo.toml
- roles/jd-server/Cargo.toml
- roles/mining-proxy/Cargo.toml
- roles/pool/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/test-utils/mining-device/Cargo.toml
- roles/translator/Cargo.toml
- utils/message-generator/Cargo.toml
same technique as for `noise_sv2` on which it is depending : adding a `#![no_std]` compliant intermediary API using the `x_with_now_rng()` so use can provide a `no_std` system time and randome number generator is the embedded system have them.
> `codec_sv2` with optional `no_std`

- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/sniffer_integration.rs
> `InterceptMessage` cleanup

- .gitignore
- roles/tests-integration/README.md
- roles/tests-integration/lib/template_provider.rs
closes #1278, alternative to #1342
unfortunately #1293 didn't fix #1278
this PR changes the directory where TP is downloaded into, replacing `/tmp` (which was giving permission errors in an undeterministic way) to a new `template-provider` directory crated at the Integration Test execution (which shouldn't ever have permission issues)
this new directory is listed on a new `.gitignore` so that we don't commit binary executables to the SRI repo, which would be bad practice
> Integration tests avoid tmp dir

- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/sniffer_integration.rs
builds on top of #1339 
closes #1317
> `integration_tests_sv2` docs cleanup

- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/sniffer_integration.rs
> Remove `replacement_mesage_type`

- roles/tests-integration/lib/sniffer.rs
> Allow backtrace print to stdout in integration tests

- roles/pool/src/lib/template_receiver/mod.rs
> Add retry logic to ensure the pool waits and connect to TP

- roles/tests-integration/lib/template_provider.rs
> retry mechanism addition to download bitcoind tarball

- common/Cargo.toml
- protocols/v1/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/roles-utils/rpc/Cargo.toml
- utils/bip32-key-derivation/Cargo.toml
- utils/error-handling/Cargo.toml
- utils/key-utils/Cargo.toml
follow-up to #1318 
I missed a few crates, which would be good to have a cleanup before we proceed with #1313
also `noise_sv2` received a new feature via #1238
> simplify `[package.metadata.docs.rs]` on remaining crates

- .github/workflows/docs.yaml
close #1311 
adds a new CI that enforces Rust Docs are not broken
> add CI for Rust Docs

- utils/message-generator/Cargo.toml
> point MG crate to crate.io, than using protocol relative path

- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/sniffer_integration.rs
> Sniffer fixes

- roles/translator/src/lib/mod.rs
> remove shutdown notification from downstream disconnect

- roles/Cargo.lock
- roles/translator/Cargo.toml
- roles/translator/src/lib/downstream_sv1/downstream.rs
- roles/translator/src/lib/mod.rs
- roles/translator/src/lib/upstream_sv2/diff_management.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
> remove async std from translator

- roles/Cargo.lock
- roles/test-utils/mining-device-sv1/Cargo.toml
- roles/test-utils/mining-device-sv1/src/client.rs
- roles/test-utils/mining-device-sv1/src/main.rs
> remove async-std from mining-device-sv1

- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/codec-sv2/src/encoder.rs
- protocols/v2/noise-sv2/Cargo.toml
- roles/Cargo.lock
- utils/Cargo.lock
- utils/buffer/Cargo.toml
Here are a couple of change to avoid `getrandom` which is [not compatible](https://docs.rs/getrandom/latest/getrandom/#unsupported-targets) with `no_std`.
> Protocols v2 no_std support

- .github/workflows/integration-tests.yaml
- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/lib/mod.rs
- roles/tests-integration/tests/jd_integration.rs
- roles/tests-integration/tests/pool_integration.rs
- roles/tests-integration/tests/sniffer_integration.rs
- roles/tests-integration/tests/translator_integration.rs
This should allow us to examine the logs from the roles that are using `tracing` crate for logging. As a default only ERROR logs will be shown, in order to examine a different level of logging, `RUST_LOG` env variable should be modified.
For example `RUST_LOG=info cargo test --test '*'`
resolves #1370
> Add `tracing-subscriber` to itf

- roles/tests-integration/lib/mod.rs
- roles/tests-integration/lib/template_provider.rs
- roles/tests-integration/lib/utils.rs
- roles/tests-integration/tests/jd_integration.rs
- roles/tests-integration/tests/pool_integration.rs
- roles/tests-integration/tests/sniffer_integration.rs
- roles/tests-integration/tests/translator_integration.rs
> `TemplateProvider` cleanup

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- protocols/v2/roles-logic-sv2/src/job_creator.rs
- protocols/v2/roles-logic-sv2/src/job_dispatcher.rs
- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
- roles/mining-proxy/src/lib/upstream_mining.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/translator/src/lib/proxy/bridge.rs
close #1436
loosely inspired by https://github.com/stratum-mining/stratum/pull/1248/commits/3f2815b5a10992158f4b04529eeb71c3c902302b from @Fi3 at #1248, but with a few corrections (and split into two different commits)
note: this renaming only happens on `roles_logic_sv2`, but not on SRI application layer (`roles`), where the field remains called `pool_signature`
> Rename `pool_signature` field of `channel_factory` into `additional_coinbase_script_data`, and change the type from `String` to `Vec<u8>`

- .github/workflows/semver-check.yaml
Currently the semver ci is failing because of outdated ci checkout version. This PR fixes that. Closes: #1495
> update action checkout version semver

- roles/test-utils/mining-device-sv1/src/client.rs
- roles/test-utils/mining-device-sv1/src/main.rs
- roles/tests-integration/lib/mod.rs
- roles/tests-integration/tests/translator_integration.rs
resolves #1484 
highest priority from my side as it blocks a couple of MG tests migration
> sv1 mining device tweaks

- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/job_creator.rs
close #1460
builds on top of #1442
> remove assumption that coinbase scriptSig prefix contains only BIP34

- protocols/v2/binary-sv2/derive_codec/src/lib.rs
Reserve internal field names & enforce checks  
- Introduced a reserved set of field names (`__decodable_internal_data`, `__decodable_internal_offset`)  
- Added a compile-time error if a struct contains a reserved field name  
- Replaced all occurrences of `data` and `offset` with the reserved identifiers  
closes: #1473
> Fix binary sv2 proc macro

- roles/pool/Cargo.toml
- roles/pool/src/lib/config.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/lib/mod.rs
- roles/pool/src/main.rs
- roles/tests-integration/lib/mod.rs
addresses #1260 and other changes
Need to complete:
> `pool` config struct changes

- protocols/fuzz-tests/src/main.rs
- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/parsers.rs
- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
- roles/jd-client/src/lib/job_declarator/setup_connection.rs
- roles/jd-client/src/lib/template_receiver/mod.rs
- roles/jd-client/src/lib/template_receiver/setup_connection.rs
- roles/jd-client/src/lib/upstream_sv2/mod.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
- roles/jd-server/src/lib/job_declarator/message_handler.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/jd-server/src/lib/mod.rs
- roles/mining-proxy/src/lib/downstream_mining.rs
- roles/mining-proxy/src/lib/error.rs
- roles/mining-proxy/src/lib/upstream_mining.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/lib/mining_pool/setup_connection.rs
- roles/pool/src/lib/template_receiver/mod.rs
- roles/pool/src/lib/template_receiver/setup_connection.rs
- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/jd_integration.rs
- roles/tests-integration/tests/pool_integration.rs
- roles/tests-integration/tests/sniffer_integration.rs
- roles/tests-integration/tests/translator_integration.rs
- roles/translator/src/lib/upstream_sv2/mod.rs
This PR remove the wrong `PoolMessages` parser, in favor of a more appropriate `AnyMessage`, as agreed on [this discussion](https://github.com/stratum-mining/stratum/discussions/1256#discussioncomment-11329317).
It needs a MAJOR bump on `roles_logic_sv2` because of the public `PoolMessages` struct which is removed in favor of the `AnyMessage` one.
Closes #1444
> `PoolMessages` removal in favor of generic `AnyMessage`

- roles/jd-client/config-examples/jdc-config-hosted-example.toml
- roles/jd-client/config-examples/jdc-config-local-example.toml
changed by accident on e185c89c7166500a66cb2db8b3e414a48682a739
this is breaking tProxy when loaded with `tproxy-config-local-jdc-example.toml`
> fix JDC listening address on example config files

- roles/tests-integration/lib/mod.rs
- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/sniffer_integration.rs
This PR adds Block from message Action to sniffer. Closes #1506
> sniffer block from message

- .github/workflows/integration-tests.yaml
this will allow us to better debug stack traces on panics
> add `RUST_BACKTRACE=1` on Integration Tests CI

- roles/pool/config-examples/pool-config-hosted-tp-example.toml
- roles/pool/config-examples/pool-config-local-tp-example.toml
- roles/pool/src/lib/config.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/lib/mod.rs
- roles/tests-integration/lib/mod.rs
- test/config/pool-mock-tp.toml
- test/config/sv1-test/pool-config.toml
Addresses #1229 by adding `shares_per_minute` to the pool configuration toml instead of hard coding to `1.0` in `pool::mining_pool::Pool::start`.
> Variable pool shares per min

- protocols/v2/const-sv2/Cargo.toml
- protocols/v2/const-sv2/src/lib.rs
- protocols/v2/roles-logic-sv2/src/handlers/template_distribution.rs
- protocols/v2/roles-logic-sv2/src/parsers.rs
- protocols/v2/subprotocols/job-declaration/src/allocate_mining_job_token.rs
- protocols/v2/subprotocols/template-distribution/src/coinbase_output_constraints.rs
- protocols/v2/subprotocols/template-distribution/src/lib.rs
- protocols/v2/sv2-ffi/src/lib.rs
- protocols/v2/sv2-ffi/sv2.h
- roles/Cargo.lock
- roles/jd-client/Cargo.toml
- roles/jd-client/src/lib/template_receiver/mod.rs
- roles/jd-server/src/lib/job_declarator/message_handler.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/pool/Cargo.toml
- roles/pool/src/lib/mod.rs
- roles/pool/src/lib/template_receiver/mod.rs
- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/pool_integration.rs
This PR adds the `coinbase_output_max_additional_sigops` and renames `CoinbaseOutputDataSize` message into `CoinbaseOutputConstraints`.
Closes #1412
> Add coinbase_output_max_additional_sigops to SRI

- .github/workflows/integration-tests.yaml
- test/integration-tests/lib/mod.rs
- test/integration-tests/lib/sniffer.rs
we're constantly getting `wait_for_message_type` timeouts on Integration Tests running on CI
while we need to find the root cause of these timeouts, waiting for 10 minutes is becoming a big bottleneck
> trying to unblock CI

- protocols/v2/roles-logic-sv2/src/parsers.rs
- test/integration-tests/lib/sniffer.rs
close #1552
example run of `test_sniffer_intercept_to_upstream` (with other tracing logs manually filtered out):
```
2025-03-11T00:37:39.785195Z  INFO integration_tests_sv2::sniffer: 🔍 Sniffer B | Forwarded: SetupConnection | Direction: ⬆
2025-03-11T00:37:39.790740Z  INFO integration_tests_sv2::sniffer: 🔍 Sniffer A | Replaced: SetupConnection with SetupConnection | Direction: ⬆
...
2025-03-11T00:37:39.794111Z  INFO integration_tests_sv2::sniffer: 🔍 Sniffer A | Forwarded: SetupConnectionSuccess | Direction: ⬇
...
2025-03-11T00:37:39.794217Z  INFO integration_tests_sv2::sniffer: 🔍 Sniffer B | Forwarded: SetupConnectionSuccess | Direction: ⬇
...
2025-03-11T00:37:39.795156Z  INFO integration_tests_sv2::sniffer: 🔍 Sniffer B | Forwarded: CoinbaseOutputDataSize | Direction: ⬆
... …
```
> add tracing to `Sniffer`

- .gitignore
- protocols/v2/roles-logic-sv2/src/parsers.rs
- roles/Cargo.lock
- roles/pool/Cargo.toml
- roles/pool/src/lib/config.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/lib/mod.rs
- roles/pool/src/lib/status.rs
- roles/pool/src/main.rs
- test/integration-tests/lib/mod.rs
- test/message-generator/test/sv1-test/sv1-test.json
> Pool unblocking + shutdown

- examples/ping-pong-encrypted/src/client.rs
- examples/ping-pong-encrypted/src/server.rs
- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
- roles/jd-client/src/lib/template_receiver/mod.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/mining-proxy/src/lib/upstream_mining.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/lib/template_receiver/mod.rs
- roles/roles-utils/network-helpers/src/noise_connection.rs
- roles/test-utils/mining-device/src/lib/mod.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
- test/integration-tests/lib/sniffer.rs
As those handles are mostly not used and they might cause ghost processes because tokio would not drop unneeded tasks if the handle is still in scope/explicitly returned.
resolves #1594
> Drop `AbortHandle` from `Connection::new`

- protocols/v1/Cargo.toml
- protocols/v2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/codec/Cargo.toml
- protocols/v2/binary-sv2/derive_codec/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/roles-utils/rpc/Cargo.toml
- utils/bip32-key-derivation/Cargo.toml
what was proposed on #1189 broke the execution of `cargo publish`
https://github.com/stratum-mining/stratum/actions/runs/14129275829/job/39585361550#step:8:12
> reintroduce versioning for internal crate dependencies

- common/Cargo.lock
- common/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- roles/Cargo.lock
- roles/jd-server/Cargo.toml
- roles/roles-utils/rpc/Cargo.toml
- utils/Cargo.lock
- utils/bip32-key-derivation/Cargo.toml
we forgot to do this on #1487
now this is breaking `cargo publish` for `roles_logic_sv2`
https://github.com/stratum-mining/stratum/actions/runs/14135355408/job/39605674363#step:20:143
close #1345
> bump `stratum-common` MAJOR version

- protocols/v2/roles-logic-sv2/Cargo.toml
it's breaking `cargo publish` for `roles_logic_sv2`
https://github.com/stratum-mining/stratum/actions/runs/14136419713/job/39609107649#step:20:142
> fix `hex-conservative` version

- test/integration-tests/lib/mod.rs
the old limitation of minimum 16 blocks was removed via https://github.com/stratum-mining/stratum/pull/1461
> TP only to generates one block for integration tests

- examples/ping-pong-encrypted/Cargo.toml
- roles/jd-client/Cargo.toml
- roles/jd-server/Cargo.toml
- roles/mining-proxy/Cargo.toml
- roles/pool/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/test-utils/mining-device-sv1/Cargo.toml
- roles/test-utils/mining-device/Cargo.toml
- roles/translator/Cargo.toml
- test/integration-tests/Cargo.lock
- test/integration-tests/Cargo.toml
- test/scale/Cargo.toml
> Use same(1.44.1) tokio version across the project

- roles/test-utils/mining-device-sv1/src/client.rs
- test/integration-tests/tests/jd_tproxy_integration.rs
- test/integration-tests/tests/translator_integration.rs
Partially addresses #1574 
This was tested on MacOS with M1 and Linux with AMD using the following script without encountering any failures.
```sh
#!/bin/bash
command_to_run="cargo test --test 'jd_tproxy_integration' -- --nocapture"
num_runs=20
success_count=0
fail_count=0
for i in $(seq 1 "$num_runs"); do
echo "Running command $i of $num_runs..."
if eval "$command_to_run"; then
echo "Run $i: Success"
((success_count++))
else
echo "Run $i: Fail"
((fail_count++))
fi
done
echo "-------------------------"
echo "Total Runs: $num_runs"
echo "Successful Runs: $success_count"
echo "Failed Runs: $fail_count"
echo "-------------------------"
```
> Reintroduce TProxy-JD integration test

- benches/benches/src/sv2/lib/client.rs
- protocols/v2/roles-logic-sv2/src/common_properties.rs
- protocols/v2/roles-logic-sv2/src/handlers/mining.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
- roles/mining-proxy/src/lib/routing_logic.rs
- roles/mining-proxy/src/lib/selectors.rs
- roles/mining-proxy/src/lib/upstream_mining.rs
- roles/test-utils/mining-device/src/lib/mod.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
This PR refactors `IsUpstream` and `IsMiningUpstream` traits inside `common_properties` to simplify generics used inside handlers, simplifying all roles as well.
While it touches `common_properties`, I still think something else is needed to fully tackle this module.
Specifically, the majority of code there is about stuff which should be managed inside the channel_logic module (which is being refactored in https://github.com/stratum-mining/stratum/pull/1624) cc @plebhash 
I'm pretty sure that after the logic is moved there, we could also think about removing `common_properties` entirely.
Partially addresses #1466
> Refactor `IsUpstream` and `IsMiningUpstream` traits to simplify generics used inside handlers

- protocols/v2/roles-logic-sv2/src/parsers.rs
Fix: this was overlooked in #1629  after changing `SubmitSolution` to `PushSolution` in JD protocol.
> #1629 followup

- roles/translator/src/lib/downstream_sv1/diff_management.rs
- roles/translator/src/lib/error.rs
- roles/translator/src/lib/proxy/bridge.rs
- roles/translator/src/lib/upstream_sv2/diff_management.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
- roles/translator/src/lib/upstream_sv2/upstream_connection.rs
Partially Resolves: #736
This PR is part of an effort to improve error handling in the translator. Currently, there are several redundant .map_err calls in the codebase, which make the code harder to read. This PR removes many of them. However, not all instances could be removed due to the use of non-Send types like MutexGuard errors, which cannot be used in Send contexts (e.g., in tokio::spawn). Addressing these cases will require more targeted changes, which we can defer until we work on those parts of the codebase.
> remove redundant map_err's in translators

- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/channels/mod.rs
- protocols/v2/roles-logic-sv2/src/channels/server/error.rs
- protocols/v2/roles-logic-sv2/src/channels/server/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/group.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/chain_tip.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/error.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/factory.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/mod.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/standard.rs
- protocols/v2/roles-logic-sv2/src/channels/server/mod.rs
- protocols/v2/roles-logic-sv2/src/channels/server/share_accounting.rs
- protocols/v2/roles-logic-sv2/src/channels/server/standard.rs
- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/lib.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/subprotocols/mining/src/lib.rs
partially addresses #1630 
so far, the APIs were designed and tested for server side functionality, namely Sv2 Pool Servers and Sv2 Job Declaration Clients (in other words, roles that actively create jobs from templates and custom jobs)
client side functionality (for Sv2 Mining Devices and Proxies) will require a follow-up PR
---
> introduce simplified APIs for channel and job logic (server side)

- protocols/v2/roles-logic-sv2/src/channels/client/error.rs
- protocols/v2/roles-logic-sv2/src/channels/client/standard.rs
- protocols/v2/roles-logic-sv2/src/channels/server/error.rs
- protocols/v2/roles-logic-sv2/src/channels/server/standard.rs
otherwise it would be possible to set a new `extranonce_prefix` that's bigger than 32 bytes, which would violate the spec and would not fit a `SetExtranoncePrefix` message
> add verification on `roles_logic_sv2::channels::*::standard::StandardChannel::set_extranonce_prefix`

- roles/pool/src/lib/mining_pool/mod.rs
fixes some small bugs from #1718
more specifically, I did `if d.group_channel.is_some()` where it should have been `if d.group_channel.is_none()`
> fix group channel handling on pool

- protocols/v2/codec-sv2/src/lib.rs
- protocols/v2/noise-sv2/src/cipher_state.rs
- protocols/v2/noise-sv2/src/initiator.rs
- protocols/v2/noise-sv2/src/lib.rs
- protocols/v2/noise-sv2/src/responder.rs
- roles/roles-utils/network-helpers/src/lib.rs
- roles/roles-utils/network-helpers/src/noise_connection.rs
This PR restructures the network_helpers noise_connection flow to make it simpler and more reliable. Previously, we were starting background tasks before completing the handshake, which made the flow confusing and likely caused ghost tasks. Now, the handshake is fully completed first, and only then are the read/write tasks spawned. We also removed the shared state wrapped in sync primitives instead, each stream gets its own cloned state, avoiding unnecessary locking since encryption and decryption are independent in Noise. Overall, this simplifies the architecture, hopefully eliminated zombie task, and makes the flow much easier to reason about.
> Simplify network helpers

- roles/pool/src/lib/mod.rs
closes #1762 
This pull request addresses an issue with the coinbase output length calculation in the `Pool` role.
The code was previously using the length of the `Vec<TxOut>` (number of outputs) to estimate the coinbase output size:
```rust
let coinbase_output_len = coinbase_output_result.len() as u32;
```
However, this approach only reflects the count of outputs, not their actual serialized size, which is critical for accurate calculation.
We now calculate the total serialized size by summing the sizes of individual `TxOut` elements. This aligns with the field’s intended purpose:
> *The maximum additional serialized bytes which the pool will add in coinbase transaction outputs.*
Here are the results with and without the fix:
**With the fix:**
**Without the fix:**
> Correct Coinbase Output Length Calculation in `Pool` Role Implementation

- .github/workflows/coverage-protocols.yaml
- .github/workflows/coverage-roles.yaml
- .github/workflows/coverage-utils.yaml
closes #1766;
This pull request updates the GitHub Actions workflow triggers for coverage testing to run on `push` events to the `main` branch instead of `pull_request` events. This ensures that coverage tests are executed after changes are merged into the main branch.
> change coverage workflows to run only when commits are pushed to main

- protocols/v2/binary-sv2/codec/src/lib.rs
- protocols/v2/roles-logic-sv2/src/channels/server/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/group.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/job_store.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/mod.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/standard.rs
- protocols/v2/roles-logic-sv2/src/channels/server/standard.rs
- roles/pool/src/lib/mining_pool/message_handler.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/translator/src/lib/error.rs
Currently, the channels structs manage jobs internally. This proposal decoubles job state from channels by utilizing a `JobStore` trait instead of using the job maps directly. A `DefaultJobStore` is also introduced that mirrors the 1-to-1 channel-to-jobstate architecture that is currently provided.
The overall goal of this proposal is to allow for more customizability (ie supporting a wider range of architectures potentially warranted by the end developer)
> decouple job state from channels with JobStore

- common/Cargo.lock
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- roles/Cargo.lock
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
This PR fixes some version bumps we did by mistake on PR https://github.com/stratum-mining/stratum/pull/1728.
- `framing_sv2` was already bumped from `4.0.0` to `5.0.0` in https://github.com/stratum-mining/stratum/pull/1667
- `common_messages_sv2` was already bumped from `4.0.0` to `5.0.0` in https://github.com/stratum-mining/stratum/pull/1654
> Fix unnecessary version bumps done by mistake

- roles/Cargo.lock
- roles/jd-client/config-examples/jdc-config-hosted-example.toml
- roles/jd-client/config-examples/jdc-config-local-example.toml
- roles/jd-client/src/lib/config.rs
- roles/jd-client/src/lib/mod.rs
- roles/jd-server/config-examples/jds-config-hosted-example.toml
- roles/jd-server/config-examples/jds-config-local-example.toml
- roles/jd-server/src/lib/config.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/pool/config-examples/pool-config-hosted-tp-example.toml
- roles/pool/config-examples/pool-config-local-tp-example.toml
- roles/pool/src/lib/config.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/lib/mod.rs
- roles/roles-utils/config-helpers/Cargo.toml
- roles/roles-utils/config-helpers/src/coinbase_output/errors.rs
- roles/roles-utils/config-helpers/src/coinbase_output/mod.rs
- roles/roles-utils/config-helpers/src/coinbase_output/serde_types.rs
- roles/roles-utils/config-helpers/src/lib.rs
- test/integration-tests/Cargo.lock
- test/integration-tests/lib/mod.rs
Fixes #1652.
Draft because I need to update the example configuration files and the documentation. But I am using this with my Bitaxes. Tried both the `raw` and the `addr` descriptor and was able to use a vanitygenned address which previously was impossible to specify.
> Allow specifying descriptors (including `raw` and `addr`) as coinbase outputs

- .github/workflows/release-libs.yaml
This PR fixes the error we are experiencing in publishing crates after a release: https://github.com/stratum-mining/stratum/actions/runs/16175295191/job/45658847493
> fix: publish dependencies before dependents in release workflow

- README.md
This PR updates the "Getting Started" link in the README to point to the correct blog URL:
🔗 From: https://stratumprotocol.org/getting-started/  
✅ To: https://stratumprotocol.org/blog/getting-started
The previous link led to a 404 page. This update ensures users can access the onboarding guide.
> Fix broken Getting Started link in README

- test/integration-tests/lib/mod.rs
- test/integration-tests/lib/template_provider.rs
closes #1183
I ran into this issue a few weeks ago on a slow connection and experienced the same problem described in it.
This PR adds a `warn`-level log message to inform users when a download is in progress. this helps clarify what’s happening during that initial delay. You can see an example of the log output in the first line of the test below:
To make this work properly, I also updated the `start_tracing` function. Previously, if `RUST_LOG` wasn’t set, the log level would default to `ERROR`. Now, it still respects `RUST_LOG` if provided, but defaults to `INFO` otherwise.
> Improve tracing defaults and add download warning log

- roles/Cargo.lock
- roles/roles-utils/rpc/Cargo.toml
- test/integration-tests/Cargo.lock
This PR bumps `rpc_sv2` to `1.1.0`, because of past changes introduced by https://github.com/stratum-mining/stratum/commit/732cc88629adfa69810c1023f26ebb76d84be011#diff-a8edde79879e48e4a33faed108f32632b83aa06146a72810793fcf4a8ecfd1cbR32-R53
Closes #1814
> Update rpc_sv2 version to 1.1.0 in Cargo.toml and Cargo.lock

- .github/workflows/semver-check.yaml
This PR adds `config_helpers_sv2` to our `semver-checks` workflow.
Follow up to PR #1811
> ci: add semver checks for config-helpers in workflow

- protocols/v2/codec-sv2/src/decoder.rs
- roles/roles-utils/network-helpers/src/lib.rs
- roles/roles-utils/network-helpers/src/noise_connection.rs
- roles/roles-utils/network-helpers/src/noise_stream.rs
- test/integration-tests/lib/utils.rs
closes: #1780
This PR introduces `NoiseTcpStream`, wrapper around a `TcpStream` that performs a noise handshake and enables encrypted, frame-based communication over TCP .
The design includes:
* A one-time Noise handshake as either `Initiator` or `Responder`
* Framed reading and writing of `StandardEitherFrame<Message>` types
* Explicit read and write halves (`NoiseTcpReadHalf`, `NoiseTcpWriteHalf`)
* Support for both blocking and non-blocking (`try_*`) frame I/O
The `NoiseTcpStream` is not a byte stream in the traditional sense. It encapsulates:
* A stateful encryption/decryption pipeline via the Noise protocol
* Frame reassembly logic required by the SV2 codec
* Buffers and internal state tightly coupled to message boundaries
Therefore, we expose only high-level, frame-based I/O …
> add noise stream

- common/Cargo.lock
- common/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- roles/Cargo.lock
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
This PR downgrades `roles_logic_sv2` to 4.0.0 since it has been MAJOR bumped twice during this milestone, while its latest [published version](https://crates.io/crates/roles_logic_sv2) is 3.0.0:
- from 3.0.0 to 4.0.0 --> https://github.com/stratum-mining/stratum/commit/cb250ac1feaf847a55b6c20c4915b9c0529b7465
- from 4.0.0 to 5.0.0 --> https://github.com/stratum-mining/stratum/commit/fd01573f4b8ff987566512fc0b7f4b7b4eb8ab54
> downgrade `roles_logic_sv2` to 4.0.0

- protocols/v2/channels-sv2/src/chain_tip.rs
- protocols/v2/channels-sv2/src/client/error.rs
- protocols/v2/channels-sv2/src/client/extended.rs
- protocols/v2/channels-sv2/src/client/group.rs
- protocols/v2/channels-sv2/src/client/mod.rs
- protocols/v2/channels-sv2/src/client/share_accounting.rs
- protocols/v2/channels-sv2/src/client/standard.rs
- protocols/v2/channels-sv2/src/lib.rs
- protocols/v2/channels-sv2/src/server/error.rs
- protocols/v2/channels-sv2/src/server/extended.rs
- protocols/v2/channels-sv2/src/server/group.rs
- protocols/v2/channels-sv2/src/server/jobs/error.rs
- protocols/v2/channels-sv2/src/server/jobs/extended.rs
- protocols/v2/channels-sv2/src/server/jobs/factory.rs
- protocols/v2/channels-sv2/src/server/jobs/job_store.rs
- protocols/v2/channels-sv2/src/server/jobs/mod.rs
- protocols/v2/channels-sv2/src/server/jobs/standard.rs
- protocols/v2/channels-sv2/src/server/mod.rs
- protocols/v2/channels-sv2/src/server/share_accounting.rs
- protocols/v2/channels-sv2/src/server/standard.rs
- protocols/v2/channels-sv2/src/target.rs
- protocols/v2/channels-sv2/src/template.rs
closes #1810 
Add missing rust docs for:
- `protocols::v2::channels_sv2`
- `protocols::v2::channels_sv2::server`
- `protocols::v2::channels_sv2::client`
- removed `set_active_job` from trait `JobStore` and replace it with `add_active_job` where needed.
Addresses a few typos
> Finishes rust docs for `channel_sv2`

- protocols/v2/channels-sv2/Cargo.toml
- protocols/v2/channels-sv2/README.md
- protocols/v2/channels-sv2/src/bip141.rs
- protocols/v2/channels-sv2/src/client/extended.rs
- protocols/v2/channels-sv2/src/client/group.rs
- protocols/v2/channels-sv2/src/client/mod.rs
- protocols/v2/channels-sv2/src/client/share_accounting.rs
- protocols/v2/channels-sv2/src/client/standard.rs
- protocols/v2/channels-sv2/src/lib.rs
- protocols/v2/channels-sv2/src/merkle_root.rs
- protocols/v2/channels-sv2/src/target.rs
- roles/Cargo.lock
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
closes #1822 ;
- Adds `hashbrown ` to replace `HashMap` and `HashSet`
- Replacing `std::io::Cursor` with `bitcoin::io::Cursor`
- Replacing `std` types and macros with `alloc` equivalents.
Updated auxiliary modules ( like merkle_root, bip141) to be `no_std` compatible types because `channels_sv2` depends on them.
> Turns `channel_sv2::client::*` `no_std` compatible

- protocols/v2/roles-logic-sv2/src/handlers/mining.rs
- roles/jd-client/src/lib/downstream.rs
- roles/pool/src/lib/mining_pool/message_handler.rs
This PR extends the legacy HandlerSv2 (old) trait `ParseMiningMessagesFromDownstream` to support `CloseChannel` message. While we could update the Pool to use the new HandlerSv2 APIs, doing so would require removing a significant amount of existing code. Instead, this PR adds CloseChannel handling to all required implementors (such as Pool and the legacy JDC).
> Add close channel method to pool

- protocols/v1/src/lib.rs
> fix: correct typo 'Startum' to 'Stratum' in V1 protocol documentation

- .github/workflows/rust-msrv.yaml
Add `--locked` to `cargo build` and `cargo test --no-run` steps in `rust-msrv.yaml` (that have a committed lock file).
Prevents CI from rewriting lockfiles.
Hopefully this produces more better error messages if you accidentally bump a crate.
> ci(msrv): enforce locked builds in MSRV workflow

- common/Cargo.lock
- protocols/v2/binary-sv2/Cargo.toml
- roles/Cargo.lock
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
CI is failing [here](https://github.com/stratum-mining/stratum/actions/runs/17987213016/job/51169619153) because `binary_sv2` is not being published, and so `subprotocols` crates are compiling old version of `binary_codec_sv2` (v2.0.0) during the workflow execution.
> bump PATCH of `binary_sv2` crate

- common/Cargo.lock
- common/Cargo.toml
- roles/Cargo.lock
- roles/roles-utils/network-helpers/Cargo.toml
- roles/roles-utils/rpc/Cargo.toml
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
- Bump network_helpers_sv2 to v4.0.1 with sv1_api ^2.1.0 dependency
- Bump stratum-common to v4.0.1 to use compatible dependencies
- Resolves codec_sv2 version conflict between v2.1.0 and v3.0.1
> Fix `stratum-common` v4.0.0 and `rpc_sv2` v1.1.0 version conflict

- roles/jd-client/src/lib/channel_manager/upstream_message_handler.rs
We were using min_extranonce during client side channel initialization, which is not correct. Use the extranonce size from upstream message as rollable extranonce.
> Fix extranonce size during client side channel initialization

- roles/roles-utils/config-helpers/src/logging.rs
This PR disable ascii code for colors when logs are stored in log files.
From this:
To this:
> Disable ascii for file

- .github/workflows/test.yaml
This PR updates the macos version used by the workflow defined in `test.yaml` from `macos-13` to `macos-latest`.
I opened this PR after reading an email by GitHub about this deprecation, more info here: https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
> ci: migrate from deprecated macos-13 to macos-latest ARM64 runner
