stratum-mining/stratum

- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/inner.rs
- protocols/v2/binary-sv2/serde-sv2/src/lib.rs
- protocols/v2/codec-sv2/src/decoder.rs
- protocols/v2/noise-sv2/src/lib.rs
- utils/buffer/benches/control_struct.rs
- utils/buffer/benches/pool_benchmark.rs
- utils/buffer/benches/pool_iai.rs
- utils/buffer/fuzz/fuzz_targets/faster.rs
- utils/buffer/fuzz/fuzz_targets/slower.rs
apologies for the nit PR - simply fixes all occurrences of a typo for the word length
> Minor nit: fix all occurrences of typo word length

- examples/interop-cpp/README.md
- examples/interop-cpp/template-provider/template-provider.cpp
- protocols/v2/sv2-ffi/src/lib.rs
- protocols/v2/sv2-ffi/sv2.h
> Style: Rename free_encoder to flush_encoder

- .github/workflows/clippy-lint.yaml
- .github/workflows/test-lint.yaml
- .github/workflows/test.yaml
Compile the property based tests in GitHub Actions.
Command:
```
% cargo test --features prop_test
```
> Add property based testing to GitHub Actions

- protocols/v2/binary-sv2/no-serde-sv2/codec/src/lib.rs
- protocols/v2/sv2-ffi/src/lib.rs
- protocols/v2/sv2-ffi/sv2.h
Addresses [this](https://github.com/stratum-mining/stratum/pull/164#issuecomment-1182963206) comment.
> Drop sv2 error in sv2 ffi

- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/subprotocols/mining/src/lib.rs
- protocols/v2/subprotocols/mining/src/open_channel.rs
- roles/v2/pool/src/lib/mining_pool/message_handler.rs
- roles/v2/pool/src/lib/mining_pool/mod.rs
> Add support for extened channel downstream pool

- Cargo.lock
- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/seq_inner.rs
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/noise-sv2/src/lib.rs
- protocols/v2/noise-sv2/src/negotiation.rs
- utils/network-helpers/src/noise_connection_async_std.rs
- utils/network-helpers/src/noise_connection_tokio.rs
> Add AES support

- LICENSE-APACHE
- LICENSE-MIT
- LICENSE.md
- Adds dual license: MIT + Apache 2.0
- Requires approval from all individuals who have previously committed to the repo
> Add license

- .github/workflows/coverage.yaml
- README.md
- Changes fail under coverage percentage from 41% -> 30%
- Add tarpaulin coverage command for local use to README
> Code cov cmd and adj percentage

- Cargo.toml
Added package info with the new license to root's cargo.toml.
> add package and license info

- .codecov.yaml
> Turn off codecov patch

- examples/ping-pong-with-noise/src/main.rs
- examples/ping-pong-without-noise/src/main.rs
Sometimes the server isn't setup yet when the client tries to connect. The client should just retry if it fails.
> 208 - retry client -> server connection if it fails 

- .github/workflows/test.yaml
- examples/interop-cpp/run.sh
- examples/ping-pong-with-noise/src/main.rs
- examples/ping-pong-with-noise/src/node.rs
- examples/ping-pong-without-noise/src/main.rs
- examples/ping-pong-without-noise/src/node.rs
- examples/sv1-client-and-server/src/main.rs
- utils/buffer/README.md
This fulfills both #70 and #71.
> 71 - Added github actions for running examples

- .githooks/pre-push
- .github/workflows/clippy-lint.yaml
- .github/workflows/sv2-header-check.yaml
- README-DEV.md
- sv2-header-check.sh
This adds a pre-push hook to the repo provided devs point their git to the new .githooks directory!
> 74 - Add pre-push hooks to repo and readme for instructions

- examples/sv1-client-and-server/src/main.rs
Replaces PR #247 because @darricksee GitHub Actions are not running.
https://github.com/stratum-mining/stratum/pull/247#issue-1384014791
> 71 - Attempt to fix client/server deadlock example in CI

- examples/sv1-client-and-server/src/main.rs
- protocols/v1/src/error.rs
- protocols/v1/src/lib.rs
- protocols/v1/src/methods/client_to_server.rs
- protocols/v1/src/methods/mod.rs
- protocols/v1/src/methods/server_to_client.rs
- protocols/v1/src/utils.rs
There are a few `todo!()` in `protocols/v1` that are required to implement for the Mock SV1 Mining Device (PR #200) required for the translator proxy (PR #190).
The Mock SV1 Mining Device PR #200 merges commits from this branch as needed. This is a separate PR into order to make things more manageable and separate out concerns.
> Some SV1 Protocol Fixes

- Cargo.lock
- Cargo.toml
- examples/sv1-client-and-server/src/main.rs
- examples/sv1-mining-device/Cargo.toml
- examples/sv1-mining-device/src/client.rs
- examples/sv1-mining-device/src/job.rs
- examples/sv1-mining-device/src/main.rs
- examples/sv1-mining-device/src/miner.rs
- protocols/v1/src/error.rs
- protocols/v1/src/lib.rs
- protocols/v1/src/methods/client_to_server.rs
- protocols/v1/src/methods/mod.rs
- protocols/v1/src/methods/server_to_client.rs
- protocols/v1/src/utils.rs
Mock SV1 Mining Device used by the translator proxy. Translator proxy PR #190 merges commits from this branch as needed. This is a separate PR into order to make things more manageable and separate out concerns.
> SV1 Mining Device

- README.md
Added sv2.h file generation and action details to readme.
> Add Instructions to Build sv2.h File in the README

- .github/workflows/test.yaml
- examples/ping-pong-without-noise/src/main.rs
- examples/ping-pong-without-noise/src/node.rs
Closes #249 
swapped out and moved sleep 
now runs on MacOs and Ubuntu
> ping-pong-without-noise Ubuntu fix

- protocols/v2/roles-logic-sv2/src/common_properties.rs
- protocols/v2/roles-logic-sv2/src/errors.rs
- protocols/v2/roles-logic-sv2/src/group_channel_logic.rs
- protocols/v2/subprotocols/mining/src/lib.rs
Add support for extranonces of different lenghts in standard channels
> Add proxy support extranonce of differnt len

- protocols/v2/subprotocols/mining/src/lib.rs
- roles/v2/pool/src/lib/mining_pool/message_handler.rs
> SV2 Pool to use bytes (not bits) as min_extranonce_size

- roles/translator/README.md
Clean up the MVP1 README to include clear run instructions.
> Translator Proxy README Instructions + Clean Up

- Cargo.lock
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/handlers/common.rs
- protocols/v2/roles-logic-sv2/src/handlers/mining.rs
- protocols/v2/roles-logic-sv2/src/handlers/mod.rs
- protocols/v2/roles-logic-sv2/src/job_creator.rs
- protocols/v2/roles-logic-sv2/src/parsers.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
- roles/translator/proxy-config.toml
- roles/translator/src/downstream_sv1/downstream.rs
- roles/translator/src/main.rs
- roles/translator/src/upstream_sv2/upstream.rs
- roles/v2/mining-proxy/proxy-config.toml
- roles/v2/mining-proxy/src/lib/downstream_mining.rs
- roles/v2/mining-proxy/src/lib/upstream_mining.rs
- roles/v2/mining-proxy/src/main.rs
- roles/v2/pool/pool-config.toml
- roles/v2/pool/src/lib/mining_pool/message_handler.rs
- roles/v2/pool/src/lib/mining_pool/mod.rs
- roles/v2/pool/src/lib/mining_pool/setup_connection.rs
- roles/v2/pool/src/lib/template_receiver/mod.rs
- roles/v2/pool/src/lib/template_receiver/setup_connection.rs
- roles/v2/pool/src/main.rs
- utils/network-helpers/Cargo.toml
- utils/network-helpers/src/noise_connection_tokio.rs
- utils/network-helpers/src/plain_connection_tokio.rs
This PR simply adds a bunch of debug statements throughout to help with troubleshooting. It also replaces naked unwraps with expects for the same reason.
> 207 - Added extra debug logging to help with troubleshooting

- protocols/v1/src/methods/server_to_client.rs
closes https://github.com/stratum-mining/stratum/issues/365.
Note: there is an open question on the linked issue asking if this needs to be considered in other array match cases in V1
> V1 Bug Fix: Match Case Ordering of mining.subscribe

- utils/message-generator/Cargo.lock
- utils/message-generator/Cargo.toml
- utils/message-generator/README.md
- utils/message-generator/src/main.rs
- utils/message-generator/src/parser/actions.rs
- utils/message-generator/src/parser/frames.rs
- utils/message-generator/src/parser/mod.rs
- utils/message-generator/src/parser/sv2_messages.rs
- utils/message-generator/test.json
Addresses #371 + #372
Adds explains user needs to update `bitcoind` + `'bitcoin-cli` information in `README` (#354)
Replaces PR #355
> message-generator doc cmts

- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/b016m.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/b0255.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/b032.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/byte_arrays/b064k.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/sequences/seq0255.rs
- protocols/v2/binary-sv2/serde-sv2/src/primitives/sequences/seq064k.rs
- utils/message-generator/src/parser/mod.rs
Hey @lorbax check this out. This fix the issue that you encountered parsing json into Sv2 sequences.
> Fix parse Sv2 sequences from json (MG)

- INTEROPERABILITY-TESTS.md
- README.md
This fills the gap needed by new users on how to properly setup 2 of easiest configurations to get started.
> Added docs around starting up the various roles

- protocols/v2/roles-logic-sv2/src/channel_logic/proxy_group_channel.rs
Added test around ordering of job found in update_new_prev_hash and corrected it to use last job per comment in #368
> Added update new prev hash test

- .gitignore
- roles/translator/src/error.rs
- roles/translator/src/main.rs
- roles/translator/src/proxy/bridge.rs
- roles/translator/src/status.rs
- roles/translator/src/upstream_sv2/upstream.rs
- roles/translator/src/upstream_sv2/upstream_connection.rs
- roles/v2/pool/pool-config.toml
Implemented error handling in the Upstream and Bridge Component so errors can be handled in the main thread. Now the TProxy will shutdown gracefully instead of panicking.
> TProxy Upstream and Bridge error handling

- test/config/pool-mock-tp.toml
- test/message-generator/messages/common_messages.json
- test/message-generator/mock/job-negotiator-mock.json
- test/message-generator/mock/template-provider-mock0.json
- test/message-generator/test/pool-mock-tp.json
- test/message-generator/test/pool-sri-test-1-standard.json
- test/message-generator/test/pool-sri-test-1.json
- test/message-generator/test/pool-sri-test-extended.json
- utils/message-generator/README.md
- utils/message-generator/src/executor.rs
- utils/message-generator/src/main.rs
- utils/message-generator/src/parser/actions.rs
- utils/message-generator/test.json
Small improvements on parsing the actiondoc
Tests: now are much better, all the common messages are separated in a module
Improved documentation
EDIT: 
- improved mocked template provider
- introduced new test where a downstream communicates with the pool through extended channel
- mocked Job Negotiator 
- improved pool-test-sri-1.json: added some steps, like submitting a valid share that meets the difficulty of the template. Mocked roles: TP and JN
> Overall improvement of MG and tests

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- roles/translator/proxy-config.toml
- roles/translator/src/downstream_sv1/diff_management.rs
- roles/translator/src/downstream_sv1/downstream.rs
- roles/translator/src/downstream_sv1/mod.rs
- roles/translator/src/main.rs
- roles/translator/src/proxy/bridge.rs
- roles/translator/src/proxy_config.rs
- roles/v2/pool/src/lib/mining_pool/mod.rs
- test/config/tproxy-config.toml
Reverts stratum-mining/stratum#523
> Revert "[WIP] Fix version mask tproxy, Add share witholdin, Fix minor issues"

- .github/workflows/coverage.yaml
- Cargo.toml
- README.md
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/utils.rs
- roles/translator/src/downstream_sv1/diff_management.rs
Proof of concept for https://github.com/stratum-mining/stratum/issues/476
> Added super_safe_lock

- protocols/v2/binary-sv2/serde-sv2/src/primitives/sequences/seq064k.rs
- protocols/v2/roles-logic-sv2/src/parsers.rs
- protocols/v2/subprotocols/job-declaration/src/declare_mining_job.rs
- protocols/v2/subprotocols/job-declaration/src/identify_transactions.rs
- protocols/v2/subprotocols/job-declaration/src/provide_missing_transactions.rs
- utils/message-generator/src/executor.rs
- utils/message-generator/src/into_static.rs
- utils/message-generator/src/parser/sv2_messages.rs
The aforementioned bugs only affects the SRI compiled using serde, so no errors are displayed.
Nevertheless, as the Message Generator uses serde, they come clear.
> This PR fixes some bugs on Message Generetor

- protocols/v2/binary-sv2/no-serde-sv2/codec/src/datatypes/non_copy_data_types/seq_inner.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/subprotocols/job-declaration/src/provide_missing_transactions.rs
- roles/jd-client/src/job_declarator/message_handler.rs
- roles/jd-client/src/job_declarator/mod.rs
- roles/jd-server/src/lib/mempool/mod.rs
This PR is reviewable, I will remove WIP as soon as I write a MG test for checking that the code works
Reviewed, MG test postponed to another PR, this is addressed in issue [661](https://github.com/stratum-mining/stratum/issues/661)
> Jdc provide missing transactions

- roles/translator/config-examples/proxy-config-local-jdc-example.toml
- roles/translator/config-examples/proxy-config-local-pool-example.toml
- roles/translator/src/downstream_sv1/diff_management.rs
- roles/translator/src/downstream_sv1/downstream.rs
- roles/translator/src/proxy_config.rs
- utils/bip32-key-derivation/Cargo.toml
This PR removes the ping mechanism introduced in PR #657 and restores the normal behaviour.
> Translator ping removal

- roles/translator/src/proxy/bridge.rs
- roles/translator/src/proxy/next_mining_notify.rs
This PR fixes the issue with translator proxy, regarding the flag `clean_jobs`.
@jakubtrnka a review from you would be appreciated 🙏
> Translator proxy `clean_jobs` fix

- roles/jd-client/src/args.rs
- roles/jd-client/src/main.rs
- roles/jd-server/src/main.rs
- roles/mining-proxy/src/main.rs
- roles/pool/src/main.rs
- roles/translator/src/args.rs
- roles/translator/src/main.rs
close https://github.com/stratum-mining/stratum/issues/685
cc @pavlenex @GitGab19
> fix role executable CLI edge cases

- roles/jd-client/config-examples/proxy-config-hosted-example.toml
- roles/jd-client/config-examples/proxy-config-local-example.toml
- roles/pool/config-examples/pool-config-hosted-tp-example.toml
- roles/pool/config-examples/pool-config-local-tp-example.toml
- roles/translator/src/downstream_sv1/diff_management.rs
- test/config/interop-jd-translator/jdc-config.toml
- test/config/interop-jd-translator/pool-config.toml
- test/config/pool-config-sri-tp-different-port.toml
- test/config/pool-config-sri-tp.toml
Since we recently upgraded our VPS, the IP set in config files needed an update.
I did it for every config file. 
In the meantime I'm currently syncing TPs on the new VPS.
I will comment under this PR when the new VPS is finally configured.
> Testnet VPS IP updated

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- protocols/v2/roles-logic-sv2/src/handlers/job_declaration.rs
> Fix some log typos

- roles/mining-proxy/config-examples/proxy-config-example.toml
close https://github.com/stratum-mining/stratum/issues/734
> fix proxy config example pubkey

- protocols/v2/noise-sv2/src/cipher_state.rs
Since #729 was on `dev` rebasing it to `main`
> Fix incorrect order of encrypt/decrypt and nonce incremental

- .github/workflows/clippy-lint.yaml
- .github/workflows/coverage.yaml
- .github/workflows/fmt.yaml
- .github/workflows/sv2-header-check.yaml
- .github/workflows/test.yaml
Fixes #762
Try commenting after CI passes...
> Don't re-run CI after review comment

- CONTRIBUTING.md
This PR adds a CONTRIBUTING.md file, so that new contributors have a document containing major guidelines to follow.
I'm looking for feedbacks and suggestions!
To have a better readability, you can review it here: https://github.com/GitGab19/stratum/blob/add-contributing-document/CONTRIBUTING.md
> Add contributing-guidelines document

- .github/workflows/run-benchmarks.yaml
This PR re-introduces the benches execution on PRs opened against `dev `branch.
> Run benchmarks on dev PRs

- benches/benches/src/sv1/lib/client.rs
- protocols/v1/src/lib.rs
- protocols/v1/src/methods/client_to_server.rs
- protocols/v1/src/methods/server_to_client.rs
> revert odd length extranonce1 patch

- protocols/v2/subprotocols/mining/src/close_channel.rs
- protocols/v2/subprotocols/mining/src/new_mining_job.rs
- protocols/v2/subprotocols/mining/src/open_channel.rs
- protocols/v2/subprotocols/mining/src/reconnect.rs
- protocols/v2/subprotocols/mining/src/set_custom_mining_job.rs
- protocols/v2/subprotocols/mining/src/set_extranonce_prefix.rs
- protocols/v2/subprotocols/mining/src/set_group_channel.rs
- protocols/v2/subprotocols/mining/src/set_new_prev_hash.rs
- protocols/v2/subprotocols/mining/src/set_target.rs
- protocols/v2/subprotocols/mining/src/submit_shares.rs
- protocols/v2/subprotocols/mining/src/update_channel.rs
- protocols/v2/subprotocols/template-distribution/src/new_template.rs
This typo was in many panic messages
> Fix typo Messaege -> Message

- protocols/v1/src/methods/client_to_server.rs
> patch `bosminer` subscribe edge case

- README.md
> add "Project Maturity" section to `README.md`

- roles/jd-server/config-examples/jds-config-hosted-example.toml
- roles/jd-server/config-examples/jds-config-local-example.toml
> config examples testnet4

- CONTRIBUTING.md
> Add commit guidance to `CONTRIBUTION.MD`

- roles/jd-server/src/lib/mod.rs
- roles/jd-server/src/lib/status.rs
Added UT for few of the files in the JDS module.
1. `/roles/jd-server/src/lib/mod.rs` - coverage : 85%
2. `/roles/jd-server/src/lib/status.rs` - coverage: 92%
> Add UT for JDS module

- INTEROPERABILITY-TESTS.md
Adds a link to the requirement on the doc about interoperability tests
> doc: Add requirements on interoperability tests

- roles/jd-client/Cargo.toml
- roles/jd-client/src/lib/error.rs
- roles/jd-client/src/lib/status.rs
- roles/jd-client/src/main.rs
- roles/jd-server/Cargo.toml
- roles/jd-server/src/lib/mod.rs
- roles/jd-server/src/main.rs
- roles/mining-proxy/Cargo.toml
- roles/mining-proxy/src/lib/mod.rs
- roles/mining-proxy/src/main.rs
- roles/pool/Cargo.toml
- roles/pool/src/lib/mining_pool/mod.rs
- roles/pool/src/main.rs
- roles/translator/Cargo.toml
- roles/translator/src/lib/error.rs
- roles/translator/src/lib/status.rs
- roles/translator/src/main.rs
> Remove toml dependency

- protocols/Cargo.lock
- protocols/v2/roles-logic-sv2/Cargo.toml
follow up to
- https://github.com/stratum-mining/stratum/pull/1088
- https://github.com/stratum-mining/stratum/pull/1084
> bump `roles_logic_sv2` version

- protocols/Cargo.lock
- protocols/v2/binary-sv2/binary-sv2/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- roles/Cargo.lock
follow up to https://github.com/stratum-mining/stratum/pull/1085
> bump `binary_sv2` version

- .github/workflows/auto-rebase.yaml
This PR add a PAT stored in repo settings, to rebase and push the PRs to be updated
> Add PAT in auto-rebase workflow

- .github/workflows/mg.yaml
Adds a basic 10 minute timeout to the sv-1 test. More investigation would be worth doing.
#1094
> test: timeout sv-1 test

- scripts/build_header.sh
- scripts/sv2-header-check.sh
> Upgrade `cbindgen` to  v0.21.0

- .github/workflows/clippy-lint.yaml
- .github/workflows/coverage.yaml
- .github/workflows/fmt.yaml
- .github/workflows/lockfiles.yaml
- .github/workflows/mg.yaml
- .github/workflows/rust-msrv.yaml
- .github/workflows/semver-check.yaml
- .github/workflows/sv2-header-check.yaml
- .github/workflows/test.yaml
> Remove dev branch occurances in ci

- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/job-declaration/README.md
- protocols/v2/subprotocols/job-declaration/src/allocate_mining_job_token.rs
- protocols/v2/subprotocols/job-declaration/src/declare_mining_job.rs
- protocols/v2/subprotocols/job-declaration/src/identify_transactions.rs
- protocols/v2/subprotocols/job-declaration/src/lib.rs
- protocols/v2/subprotocols/job-declaration/src/provide_missing_transactions.rs
- protocols/v2/subprotocols/job-declaration/src/submit_solution.rs
> Job Declaration Documentation

- roles/tests-integration/tests/common/sniffer.rs
close https://github.com/stratum-mining/stratum/issues/1282
this PR adds a new method `Sniffer::wait_for_message_type` which takes two parameters:
- `message_direction: MessageDirection`
- `message_type: u8`
the function will return execution as soon as there's some expected message type on some `Sniffer` FIFO (either downstream or upstream)
this can be used to hold the execution of the tokio runtime of some Integration Test
it's useful when we don't know beforehand how long it could take to e.g.: find a share
> `Sniffer::wait_for_message_type`

- .github/workflows/mg.yaml
follow up to https://github.com/stratum-mining/stratum/pull/1262
closes https://github.com/stratum-mining/stratum/issues/1208
> disable MG tproxy CI

- README.md
adding vinteum to the supporters, like in https://github.com/stratum-mining/stratumprotocol.org/pull/242
rendering: https://github.com/plebhash/stratum/tree/vinteum_readme#-supporters
> add vinteum to README

- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/lib/template_provider.rs
> replace bitcoind with corpc-node crate

- roles/Cargo.lock
- roles/roles-utils/network-helpers/Cargo.toml
- roles/translator/Cargo.toml
> remove with_serde from roles

- roles/jd-client/src/lib/job_declarator/mod.rs
> additional check on `template_id` before updating `last_set_new_prev_hash` on JDC

- roles/tests-integration/tests/jd_integration.rs
> Test JDC connection with TP

- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/lib/mod.rs
> remove env-filter

- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/lib/mod.rs
- roles/tests-integration/tests/sv2_mining_device.rs
resolves #1525
should unblock #1476
> Add sv2 mining device to itf

- roles/tests-integration/lib/template_provider.rs
> Prevent TP from immediately failing

- utils/Cargo.lock
- utils/bip32-key-derivation/Cargo.toml
- utils/bip32-key-derivation/src/lib.rs
- utils/bip32-key-derivation/src/main.rs
Updates to repository level bitcoin crate version.
> refactor: update dependencies for bip32 key derivation util

- roles/jd-client/src/lib/job_declarator/mod.rs
> `prev_hash` addition in `LastDeclareJob` to avoid using a wrong prev_hash for `non-future` templates/jobs

- protocols/v2/roles-logic-sv2/src/utils.rs
- roles/translator/src/lib/downstream_sv1/diff_management.rs
> Manage aritmetic overflow in `hashrate_from_target`

- roles/Cargo.lock
- roles/tests-integration/Cargo.toml
- roles/tests-integration/lib/mod.rs
> Organise deps in integration-tests crate

- roles/tests-integration/lib/sniffer.rs
- roles/tests-integration/tests/sniffer_integration.rs
as described here https://github.com/stratum-mining/stratum/issues/1506#issuecomment-2710808939 the previous scope from #1510 was doing more than needed
close #1506
> change `IgnoreFromMessage` to `IgnoreMessage`

- roles/tests-integration/tests/jd_integration.rs
- roles/tests-integration/tests/pool_integration.rs
- roles/tests-integration/tests/sniffer_integration.rs
> add tracing to all IT test

- common/src/lib.rs
- roles/jd-server/src/lib/config.rs
- roles/jd-server/src/lib/mempool/mod.rs
- roles/jd-server/src/lib/mod.rs
- roles/jd-server/src/main.rs
- roles/roles-utils/rpc/src/lib.rs
- roles/roles-utils/rpc/src/mini_rpc_client.rs
- roles/tests-integration/lib/mod.rs
Use `hyper::Uri` exported from `rpc_sv2` instead.
resolves #1513
> Remove `stratum_common::url`

- test/integration-tests/lib/mod.rs
> extend start mining-sv2-proxy to accept multiple upstreams

- test/integration-tests/lib/template_provider.rs
> Add wallet API to `TemplateProvider`

- .github/workflows/rust-msrv.yaml
- roles/Cargo.lock
we accidentally broke MSRV on #1554
> fix MSRV for `roles/Cargo.lock`

- protocols/v2/noise-sv2/Cargo.toml
- roles/Cargo.lock
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
- utils/key-utils/Cargo.toml
> final version bumps for `v1.3.0` release

- protocols/v2/roles-logic-sv2/src/utils.rs
- test/integration-tests/lib/mod.rs
- test/integration-tests/lib/sniffer.rs
- test/integration-tests/lib/sv1_sniffer.rs
- test/integration-tests/lib/template_provider.rs
- test/integration-tests/tests/jd_integration.rs
- test/integration-tests/tests/jdc_fallback.rs
- test/integration-tests/tests/pool_integration.rs
- test/integration-tests/tests/sniffer_integration.rs
- test/integration-tests/tests/sv1.rs
- test/integration-tests/tests/sv2_mining_device.rs
- test/integration-tests/tests/translator_integration.rs
> Make `Sniffer` unblocking and upgrade TP

- .github/workflows/semver-check.yaml
> rust `1.85` set in cargo-semver-check workflow

- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- roles/pool/src/lib/mining_pool/message_handler.rs
- roles/translator/src/lib/upstream_sv2/diff_management.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
> Improve UpdateChannel/SetTarget handling on Pool and tProxy

- examples/ping-pong-encrypted/src/client.rs
- examples/ping-pong-encrypted/src/server.rs
- examples/ping-pong/src/client.rs
- examples/ping-pong/src/server.rs
- roles/mining-proxy/src/lib/mod.rs
- roles/mining-proxy/src/main.rs
- roles/translator/src/lib/config.rs
- roles/translator/src/lib/downstream_sv1/diff_management.rs
- roles/translator/src/lib/downstream_sv1/downstream.rs
- roles/translator/src/lib/mod.rs
- roles/translator/src/lib/proxy_config.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
- roles/translator/src/main.rs
- test/integration-tests/lib/mod.rs
> Renaming of `translator config` and `mining proxy config`

- roles/jd-server/src/lib/config.rs
- roles/jd-server/src/lib/error.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- roles/jd-server/src/lib/mempool/error.rs
- roles/jd-server/src/lib/mempool/mod.rs
- roles/jd-server/src/lib/mod.rs
- roles/jd-server/src/lib/status.rs
- roles/jd-server/src/main.rs
This PR improves the documentation on our current JDS.
In addition to this, I created a doc to wrap the main points of discussion wrt the current state of it.
It can be read here: https://hackmd.io/@qEJlsHMITwOhWK3crvYK4A/rknEhI6Ryg
Closes #1472
> JDS documentation improvements

- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/channel_logic/channel_factory.rs
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/mining/src/set_custom_mining_job.rs
- roles/Cargo.lock
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
> Remove `SetCustomMiningJob::extranonce_size`

- roles/Cargo.lock
- test/integration-tests/Cargo.lock
- test/integration-tests/Cargo.toml
> Upgrade `corepc` to `0.7.0`

- roles/translator/Dockerfile.dev
> remove dockerfile from tproxy

- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/common-messages/src/setup_connection.rs
- protocols/v2/subprotocols/job-declaration/src/allocate_mining_job_token.rs
- protocols/v2/subprotocols/job-declaration/src/declare_mining_job.rs
- protocols/v2/subprotocols/job-declaration/src/provide_missing_transactions.rs
- protocols/v2/subprotocols/job-declaration/src/push_solution.rs
- protocols/v2/sv2-ffi/Cargo.toml
- roles/Cargo.lock
- roles/jd-client/src/lib/job_declarator/setup_connection.rs
- roles/jd-client/src/lib/template_receiver/mod.rs
- roles/jd-server/config-examples/jds-config-hosted-example.toml
- roles/jd-server/config-examples/jds-config-local-example.toml
- roles/jd-server/src/lib/config.rs
- roles/jd-server/src/lib/job_declarator/message_handler.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
- test/integration-tests/Cargo.lock
> Change async mining terminology

- roles/translator/src/args.rs
- roles/translator/src/lib/config.rs
- roles/translator/src/lib/downstream_sv1/diff_management.rs
- roles/translator/src/lib/downstream_sv1/downstream.rs
- roles/translator/src/lib/downstream_sv1/mod.rs
- roles/translator/src/lib/error.rs
- roles/translator/src/lib/mod.rs
- roles/translator/src/lib/proxy/bridge.rs
- roles/translator/src/lib/proxy/next_mining_notify.rs
- roles/translator/src/lib/status.rs
- roles/translator/src/lib/upstream_sv2/diff_management.rs
- roles/translator/src/lib/upstream_sv2/mod.rs
- roles/translator/src/lib/upstream_sv2/upstream.rs
- roles/translator/src/lib/upstream_sv2/upstream_connection.rs
- roles/translator/src/lib/utils.rs
- roles/translator/src/main.rs
closes: #1479
Detailed analysis can be found here: https://hackmd.io/@RDfBQ-d7RouOwG9UCv_w7g/rkepl6ygll
> Add translator docs

- common/src/constants/mod.rs
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/codec-sv2/examples/encrypted.rs
- protocols/v2/codec-sv2/src/decoder.rs
- protocols/v2/codec-sv2/src/encoder.rs
- protocols/v2/codec-sv2/src/lib.rs
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/framing-sv2/src/header.rs
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/sv2-ffi/sv2.h
- roles/Cargo.lock
- roles/roles-utils/network-helpers/src/lib.rs
> SV2 Constants Cleanup

- roles/jd-client/src/args.rs
- roles/jd-client/src/lib/config.rs
- roles/jd-client/src/lib/downstream.rs
- roles/jd-client/src/lib/error.rs
- roles/jd-client/src/lib/job_declarator/message_handler.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
- roles/jd-client/src/lib/job_declarator/setup_connection.rs
- roles/jd-client/src/lib/mod.rs
- roles/jd-client/src/lib/status.rs
- roles/jd-client/src/lib/template_receiver/message_handler.rs
- roles/jd-client/src/lib/template_receiver/mod.rs
- roles/jd-client/src/lib/template_receiver/setup_connection.rs
- roles/jd-client/src/lib/upstream_sv2/upstream.rs
- roles/jd-client/src/main.rs
> add jdc doc

- test/integration-tests/Cargo.lock
- test/integration-tests/lib/interceptor.rs
- test/integration-tests/lib/message_aggregator.rs
- test/integration-tests/lib/mod.rs
- test/integration-tests/lib/sniffer.rs
- test/integration-tests/lib/sniffer_error.rs
- test/integration-tests/lib/sv1_sniffer.rs
- test/integration-tests/lib/types.rs
- test/integration-tests/lib/utils.rs
- test/integration-tests/tests/jd_integration.rs
- test/integration-tests/tests/jd_provide_missing_transaction.rs
- test/integration-tests/tests/jd_tproxy_integration.rs
- test/integration-tests/tests/jdc_block_propogation.rs
- test/integration-tests/tests/jdc_fallback.rs
- test/integration-tests/tests/jds_block_propogation.rs
- test/integration-tests/tests/pool_integration.rs
- test/integration-tests/tests/sniffer_integration.rs
- test/integration-tests/tests/sv1.rs
- test/integration-tests/tests/sv2_mining_device.rs
- test/integration-tests/tests/translator_integration.rs
resolves #1661 
I also thought about removing the `check_on_drop` flag as it is not used. It can result in a removal of a few lines of code and simplify others. wdyt?
> Combine `Sniffer` integration tests

- roles/jd-client/run.sh
> remove run.sh from jd-client

- test/integration-tests/lib/mock_downstream.rs
- test/integration-tests/lib/mod.rs
~~Blocked by #1662~~
Partially resolves #1670
> Add `MockDownstream`

- roles/jd-client/src/main.rs
- roles/jd-server/src/main.rs
- roles/mining-proxy/src/main.rs
- roles/pool/src/main.rs
- roles/test-utils/mining-device/src/main.rs
- roles/translator/src/main.rs
> remove special library naming in roles

- protocols/v2/roles-logic-sv2/src/channels/server/error.rs
- protocols/v2/roles-logic-sv2/src/channels/server/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/group.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/error.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/factory.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/standard.rs
- protocols/v2/roles-logic-sv2/src/channels/server/standard.rs
- protocols/v2/roles-logic-sv2/src/errors.rs
- roles/pool/config-examples/pool-config-hosted-tp-example.toml
- roles/pool/config-examples/pool-config-local-tp-example.toml
- roles/pool/src/lib/config.rs
- roles/pool/src/lib/mining_pool/message_handler.rs
- roles/pool/src/lib/mining_pool/mod.rs
- roles/test-utils/mining-device/src/lib/mod.rs
- roles/translator/src/lib/upstream_sv2/diff_management.rs
- test/integration-tests/lib/mod.rs
close #1631 
to be merged after ~#1672~  #1724
> migrate Pool to new `channels` module of `roles_logic_sv2`

- protocols/v2/subprotocols/job-declaration/src/allocate_mining_job_token.rs
- roles/jd-client/src/lib/template_receiver/mod.rs
- roles/jd-server/src/lib/job_declarator/message_handler.rs
- roles/jd-server/src/lib/job_declarator/mod.rs
close #1733
to be merged after #1745
> remove redudant fields from `AllocateMiningJobToken.Success`

- .github/workflows/test.yaml
> cover crate examples on CI

- protocols/v2/roles-logic-sv2/src/channels/server/jobs/error.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/extended.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/factory.rs
- protocols/v2/roles-logic-sv2/src/channels/server/jobs/standard.rs
- protocols/v2/roles-logic-sv2/src/utils.rs
- roles/jd-client/src/lib/job_declarator/mod.rs
- test/integration-tests/tests/jdc_receives_submit_shares_success.rs
> fix coinbase deserialization

- protocols/v2/roles-logic-sv2/src/errors.rs
- roles/pool/src/lib/mining_pool/message_handler.rs
> add check on coinbase output script pubkey for custom job on Pool

- roles/pool/src/lib/mining_pool/message_handler.rs
- roles/pool/src/lib/mining_pool/mod.rs
> fix unnecessary creation of group channels on pool

- common/Cargo.toml
- protocols/v1/Cargo.toml
- protocols/v2/binary-sv2/Cargo.toml
- protocols/v2/binary-sv2/codec/Cargo.toml
- protocols/v2/binary-sv2/derive_codec/Cargo.toml
- protocols/v2/channels-sv2/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/handlers-sv2/Cargo.toml
- protocols/v2/noise-sv2/Cargo.toml
- protocols/v2/parsers-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- protocols/v2/sv2-ffi/Cargo.toml
- roles/jd-server/Cargo.toml
- roles/pool/Cargo.toml
- roles/roles-utils/config-helpers/Cargo.toml
- roles/roles-utils/network-helpers/Cargo.toml
- roles/test-utils/mining-device-sv1/Cargo.toml
- roles/test-utils/mining-device-sv1/src/client.rs
- roles/test-utils/mining-device/Cargo.toml
- test/integration-tests/Cargo.toml
- test/integration-tests/lib/template_provider.rs
- test/integration-tests/lib/utils.rs
- utils/buffer/Cargo.toml
- utils/buffer/fuzz/Cargo.toml
closes #1666 ;
Updates all roles crates to edition 2021 where needed;
> Update roles rust edition to 2021

- test/integration-tests/lib/interceptor.rs
- test/integration-tests/lib/sniffer.rs
- test/integration-tests/lib/utils.rs
closes #1854
Adds logging of the data from messages forwarded through the Sniffer.
> improve sniffer logging data

- protocols/v2/channels-sv2/Cargo.toml
- protocols/v2/handlers-sv2/Cargo.toml
- protocols/v2/parsers-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/Cargo.toml
- protocols/v2/roles-logic-sv2/src/utils.rs
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/job-declaration/src/declare_mining_job.rs
- roles/Cargo.lock
- roles/jd-client/src/lib/job_declarator/mod.rs
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
closes #1847 ;
Changes the field name to match the specs, adjusts the comments and update where needed
This change required a new major bump
> fix the divergence of field names in DeclareMiningJob

- protocols/v1/src/json_rpc.rs
- test/integration-tests/lib/sv1_sniffer.rs
> implements display traits for sv1 messages

- common/Cargo.lock
- common/Cargo.toml
- protocols/v1/Cargo.toml
- protocols/v2/binary-sv2/Cargo.toml
- protocols/v2/channels-sv2/Cargo.toml
- protocols/v2/codec-sv2/Cargo.toml
- protocols/v2/framing-sv2/Cargo.toml
- protocols/v2/handlers-sv2/Cargo.toml
- protocols/v2/parsers-sv2/Cargo.toml
- protocols/v2/subprotocols/common-messages/Cargo.toml
- protocols/v2/subprotocols/job-declaration/Cargo.toml
- protocols/v2/subprotocols/mining/Cargo.toml
- protocols/v2/subprotocols/template-distribution/Cargo.toml
- roles/Cargo.lock
- roles/roles-utils/rpc/Cargo.toml
- roles/roles-utils/stratum-translation/Cargo.toml
- test/integration-tests/Cargo.lock
- utils/Cargo.lock
- utils/bip32-key-derivation/Cargo.toml
Fix for https://github.com/stratum-mining/stratum/actions/runs/17989299334/job/51175341121
> specify dependencies versions of `stratum_translation` crate

- protocols/v2/handlers-sv2/Cargo.toml
- protocols/v2/handlers-sv2/README.md
> add readme to handlers_sv2

- roles/translator/src/lib/sv1/downstream/downstream.rs
This PR improves the way messages received by the Sv1Server in downstream.rs are managed.
It fixes an issue reported by @plebhash and @lucasbalieiro for which the `jd_tproxy_integration` test was sometimes failing on macos.
> tProxy: improve Sv1Server messages received in downstream.rs
